package com.feast.kanjo.entity;

public class Lbm83ChohyokanriPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbm83_chohyokanri_pkey.chohyoshbtsuid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String chohyoshbtsuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbm83_chohyokanri_pkey.chohyoshbtsuid
     *
     * @return the value of lb01_pt.lbm83_chohyokanri_pkey.chohyoshbtsuid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getChohyoshbtsuid() {
        return chohyoshbtsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbm83_chohyokanri_pkey.chohyoshbtsuid
     *
     * @param chohyoshbtsuid the value for lb01_pt.lbm83_chohyokanri_pkey.chohyoshbtsuid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setChohyoshbtsuid(String chohyoshbtsuid) {
        this.chohyoshbtsuid = chohyoshbtsuid;
    }
}