package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbm81BatResult;
import com.feast.kanjo.entity.Lbm81BatResultExample;
import com.feast.kanjo.entity.Lbm81BatResultKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbm81BatResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int countByExample(Lbm81BatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByExample(Lbm81BatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByPrimaryKey(Lbm81BatResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insert(Lbm81BatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insertSelective(Lbm81BatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    List<Lbm81BatResult> selectByExample(Lbm81BatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    Lbm81BatResult selectByPrimaryKey(Lbm81BatResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbm81BatResult record, @Param("example") Lbm81BatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExample(@Param("record") Lbm81BatResult record, @Param("example") Lbm81BatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByPrimaryKeySelective(Lbm81BatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbm81_bat_result
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByPrimaryKey(Lbm81BatResult record);
}