package com.feast.kanjo.entity;

public class Lbt04BaikanYPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer nendo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String sysgrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kgygrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tencd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shohincd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shohincd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shohincd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shohincd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shohincd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String sibtcd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String sibtcd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tnpncd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tnpncd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shiirekbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String gnkkbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String dskbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt04_baikan_y_pkey.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String riekicmpkbn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.nendo
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getNendo() {
        return nendo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.nendo
     *
     * @param nendo the value for lb01_pt.lbt04_baikan_y_pkey.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setNendo(Integer nendo) {
        this.nendo = nendo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.sysgrpcd
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getSysgrpcd() {
        return sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.sysgrpcd
     *
     * @param sysgrpcd the value for lb01_pt.lbt04_baikan_y_pkey.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSysgrpcd(String sysgrpcd) {
        this.sysgrpcd = sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.kgygrpcd
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKgygrpcd() {
        return kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.kgygrpcd
     *
     * @param kgygrpcd the value for lb01_pt.lbt04_baikan_y_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKgygrpcd(String kgygrpcd) {
        this.kgygrpcd = kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.tencd
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTencd() {
        return tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.tencd
     *
     * @param tencd the value for lb01_pt.lbt04_baikan_y_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTencd(String tencd) {
        this.tencd = tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd1
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShohincd1() {
        return shohincd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd1
     *
     * @param shohincd1 the value for lb01_pt.lbt04_baikan_y_pkey.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShohincd1(String shohincd1) {
        this.shohincd1 = shohincd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd2
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShohincd2() {
        return shohincd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd2
     *
     * @param shohincd2 the value for lb01_pt.lbt04_baikan_y_pkey.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShohincd2(String shohincd2) {
        this.shohincd2 = shohincd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd3
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShohincd3() {
        return shohincd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd3
     *
     * @param shohincd3 the value for lb01_pt.lbt04_baikan_y_pkey.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShohincd3(String shohincd3) {
        this.shohincd3 = shohincd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd4
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShohincd4() {
        return shohincd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd4
     *
     * @param shohincd4 the value for lb01_pt.lbt04_baikan_y_pkey.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShohincd4(String shohincd4) {
        this.shohincd4 = shohincd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd5
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShohincd5() {
        return shohincd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shohincd5
     *
     * @param shohincd5 the value for lb01_pt.lbt04_baikan_y_pkey.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShohincd5(String shohincd5) {
        this.shohincd5 = shohincd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd1
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getSibtcd1() {
        return sibtcd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd1
     *
     * @param sibtcd1 the value for lb01_pt.lbt04_baikan_y_pkey.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSibtcd1(String sibtcd1) {
        this.sibtcd1 = sibtcd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd2
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getSibtcd2() {
        return sibtcd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.sibtcd2
     *
     * @param sibtcd2 the value for lb01_pt.lbt04_baikan_y_pkey.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSibtcd2(String sibtcd2) {
        this.sibtcd2 = sibtcd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd1
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTnpncd1() {
        return tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd1
     *
     * @param tnpncd1 the value for lb01_pt.lbt04_baikan_y_pkey.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTnpncd1(String tnpncd1) {
        this.tnpncd1 = tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd2
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTnpncd2() {
        return tnpncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.tnpncd2
     *
     * @param tnpncd2 the value for lb01_pt.lbt04_baikan_y_pkey.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTnpncd2(String tnpncd2) {
        this.tnpncd2 = tnpncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.shiirekbn
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShiirekbn() {
        return shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.shiirekbn
     *
     * @param shiirekbn the value for lb01_pt.lbt04_baikan_y_pkey.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShiirekbn(String shiirekbn) {
        this.shiirekbn = shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.gnkkbn
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getGnkkbn() {
        return gnkkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.gnkkbn
     *
     * @param gnkkbn the value for lb01_pt.lbt04_baikan_y_pkey.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setGnkkbn(String gnkkbn) {
        this.gnkkbn = gnkkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.dskbn
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getDskbn() {
        return dskbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.dskbn
     *
     * @param dskbn the value for lb01_pt.lbt04_baikan_y_pkey.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setDskbn(String dskbn) {
        this.dskbn = dskbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt04_baikan_y_pkey.riekicmpkbn
     *
     * @return the value of lb01_pt.lbt04_baikan_y_pkey.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getRiekicmpkbn() {
        return riekicmpkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt04_baikan_y_pkey.riekicmpkbn
     *
     * @param riekicmpkbn the value for lb01_pt.lbt04_baikan_y_pkey.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setRiekicmpkbn(String riekicmpkbn) {
        this.riekicmpkbn = riekicmpkbn;
    }
}