package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt03BaikanK;
import com.feast.kanjo.entity.Lbt03BaikanKExample;
import com.feast.kanjo.entity.Lbt03BaikanKKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt03BaikanKMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbt03BaikanKExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbt03BaikanKExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Lbt03BaikanKKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbt03BaikanK record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbt03BaikanK record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbt03BaikanK> selectByExample(Lbt03BaikanKExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Lbt03BaikanK selectByPrimaryKey(Lbt03BaikanKKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt03BaikanK record, @Param("example") Lbt03BaikanKExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbt03BaikanK record, @Param("example") Lbt03BaikanKExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt03BaikanK record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt03_baikan_k
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Lbt03BaikanK record);
}