package com.feast.kanjo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Lbt21TanaMeisai extends Lbt21TanaMeisaiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tanaymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Integer tanaymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.bmncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String bmncd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.bmncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String bmncd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.bmncd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String bmncd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String sibtcd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String sibtcd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tnpncd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tnpncd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shiirekbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String gnkkbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String dskbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String riekicmpkbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tanajisshiymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tanajisshiymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.kkriincd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String kkriincd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.terminalno
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String terminalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tsuketatekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tsuketatekbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tanano
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tanano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.dansu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String dansu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.gyonotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Integer gyonotana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.tankatana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal tankatana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.suryotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal suryotana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.kingaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Long kingaku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shomigaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Long shomigaku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.nefudakb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String nefudakb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.nefudazeikb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String nefudazeikb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.zeiritsu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal zeiritsu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.shoyojikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Short shoyojikan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvnum1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal rsvnum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvnum2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal rsvnum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvnum3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal rsvnum3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvnum4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal rsvnum4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvnum5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private BigDecimal rsvnum5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvkbn1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String rsvkbn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvkbn2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String rsvkbn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvkbn3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String rsvkbn3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvkbn4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String rsvkbn4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.rsvkbn5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String rsvkbn5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.kakuteiflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String kakuteiflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.chohyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String chohyono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errgyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Short errgyono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb6
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb7
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb8
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb9
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb10
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb11
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb12
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb14
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb15
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb16
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb17
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb18
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb19
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb20
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb21
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb22
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb23
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb24
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb25
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb26
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb27
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb28
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb29
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.errkb30
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String errkb30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.delflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String delflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Date deldte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Date instdte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String instusrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String instprgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String insipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Date upddte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String updusrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String updprgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt21_tana_meisai.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String updipaddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tanaymd
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tanaymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Integer getTanaymd() {
        return tanaymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tanaymd
     *
     * @param tanaymd the value for lb01_pt.lbt21_tana_meisai.tanaymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTanaymd(Integer tanaymd) {
        this.tanaymd = tanaymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.bmncd1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.bmncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getBmncd1() {
        return bmncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.bmncd1
     *
     * @param bmncd1 the value for lb01_pt.lbt21_tana_meisai.bmncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setBmncd1(String bmncd1) {
        this.bmncd1 = bmncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.bmncd2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.bmncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getBmncd2() {
        return bmncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.bmncd2
     *
     * @param bmncd2 the value for lb01_pt.lbt21_tana_meisai.bmncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setBmncd2(String bmncd2) {
        this.bmncd2 = bmncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.bmncd3
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.bmncd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getBmncd3() {
        return bmncd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.bmncd3
     *
     * @param bmncd3 the value for lb01_pt.lbt21_tana_meisai.bmncd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setBmncd3(String bmncd3) {
        this.bmncd3 = bmncd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shohincd1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd1() {
        return shohincd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shohincd1
     *
     * @param shohincd1 the value for lb01_pt.lbt21_tana_meisai.shohincd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd1(String shohincd1) {
        this.shohincd1 = shohincd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shohincd2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd2() {
        return shohincd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shohincd2
     *
     * @param shohincd2 the value for lb01_pt.lbt21_tana_meisai.shohincd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd2(String shohincd2) {
        this.shohincd2 = shohincd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shohincd3
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd3() {
        return shohincd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shohincd3
     *
     * @param shohincd3 the value for lb01_pt.lbt21_tana_meisai.shohincd3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd3(String shohincd3) {
        this.shohincd3 = shohincd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shohincd4
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd4() {
        return shohincd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shohincd4
     *
     * @param shohincd4 the value for lb01_pt.lbt21_tana_meisai.shohincd4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd4(String shohincd4) {
        this.shohincd4 = shohincd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shohincd5
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd5() {
        return shohincd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shohincd5
     *
     * @param shohincd5 the value for lb01_pt.lbt21_tana_meisai.shohincd5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd5(String shohincd5) {
        this.shohincd5 = shohincd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.sibtcd1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getSibtcd1() {
        return sibtcd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.sibtcd1
     *
     * @param sibtcd1 the value for lb01_pt.lbt21_tana_meisai.sibtcd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setSibtcd1(String sibtcd1) {
        this.sibtcd1 = sibtcd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.sibtcd2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getSibtcd2() {
        return sibtcd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.sibtcd2
     *
     * @param sibtcd2 the value for lb01_pt.lbt21_tana_meisai.sibtcd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setSibtcd2(String sibtcd2) {
        this.sibtcd2 = sibtcd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tnpncd1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTnpncd1() {
        return tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tnpncd1
     *
     * @param tnpncd1 the value for lb01_pt.lbt21_tana_meisai.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTnpncd1(String tnpncd1) {
        this.tnpncd1 = tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tnpncd2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTnpncd2() {
        return tnpncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tnpncd2
     *
     * @param tnpncd2 the value for lb01_pt.lbt21_tana_meisai.tnpncd2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTnpncd2(String tnpncd2) {
        this.tnpncd2 = tnpncd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shiirekbn
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShiirekbn() {
        return shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shiirekbn
     *
     * @param shiirekbn the value for lb01_pt.lbt21_tana_meisai.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShiirekbn(String shiirekbn) {
        this.shiirekbn = shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.gnkkbn
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getGnkkbn() {
        return gnkkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.gnkkbn
     *
     * @param gnkkbn the value for lb01_pt.lbt21_tana_meisai.gnkkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setGnkkbn(String gnkkbn) {
        this.gnkkbn = gnkkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.dskbn
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getDskbn() {
        return dskbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.dskbn
     *
     * @param dskbn the value for lb01_pt.lbt21_tana_meisai.dskbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setDskbn(String dskbn) {
        this.dskbn = dskbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.riekicmpkbn
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRiekicmpkbn() {
        return riekicmpkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.riekicmpkbn
     *
     * @param riekicmpkbn the value for lb01_pt.lbt21_tana_meisai.riekicmpkbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRiekicmpkbn(String riekicmpkbn) {
        this.riekicmpkbn = riekicmpkbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tanajisshiymd
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tanajisshiymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTanajisshiymd() {
        return tanajisshiymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tanajisshiymd
     *
     * @param tanajisshiymd the value for lb01_pt.lbt21_tana_meisai.tanajisshiymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTanajisshiymd(String tanajisshiymd) {
        this.tanajisshiymd = tanajisshiymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.kkriincd
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.kkriincd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getKkriincd() {
        return kkriincd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.kkriincd
     *
     * @param kkriincd the value for lb01_pt.lbt21_tana_meisai.kkriincd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setKkriincd(String kkriincd) {
        this.kkriincd = kkriincd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.terminalno
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.terminalno
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTerminalno() {
        return terminalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.terminalno
     *
     * @param terminalno the value for lb01_pt.lbt21_tana_meisai.terminalno
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTerminalno(String terminalno) {
        this.terminalno = terminalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tsuketatekbn
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tsuketatekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTsuketatekbn() {
        return tsuketatekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tsuketatekbn
     *
     * @param tsuketatekbn the value for lb01_pt.lbt21_tana_meisai.tsuketatekbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTsuketatekbn(String tsuketatekbn) {
        this.tsuketatekbn = tsuketatekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tanano
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tanano
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTanano() {
        return tanano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tanano
     *
     * @param tanano the value for lb01_pt.lbt21_tana_meisai.tanano
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTanano(String tanano) {
        this.tanano = tanano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.dansu
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.dansu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getDansu() {
        return dansu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.dansu
     *
     * @param dansu the value for lb01_pt.lbt21_tana_meisai.dansu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setDansu(String dansu) {
        this.dansu = dansu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.gyonotana
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.gyonotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Integer getGyonotana() {
        return gyonotana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.gyonotana
     *
     * @param gyonotana the value for lb01_pt.lbt21_tana_meisai.gyonotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setGyonotana(Integer gyonotana) {
        this.gyonotana = gyonotana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.tankatana
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.tankatana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getTankatana() {
        return tankatana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.tankatana
     *
     * @param tankatana the value for lb01_pt.lbt21_tana_meisai.tankatana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTankatana(BigDecimal tankatana) {
        this.tankatana = tankatana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.suryotana
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.suryotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getSuryotana() {
        return suryotana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.suryotana
     *
     * @param suryotana the value for lb01_pt.lbt21_tana_meisai.suryotana
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setSuryotana(BigDecimal suryotana) {
        this.suryotana = suryotana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.kingaku
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.kingaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Long getKingaku() {
        return kingaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.kingaku
     *
     * @param kingaku the value for lb01_pt.lbt21_tana_meisai.kingaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setKingaku(Long kingaku) {
        this.kingaku = kingaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shomigaku
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shomigaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Long getShomigaku() {
        return shomigaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shomigaku
     *
     * @param shomigaku the value for lb01_pt.lbt21_tana_meisai.shomigaku
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShomigaku(Long shomigaku) {
        this.shomigaku = shomigaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.nefudakb
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.nefudakb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getNefudakb() {
        return nefudakb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.nefudakb
     *
     * @param nefudakb the value for lb01_pt.lbt21_tana_meisai.nefudakb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setNefudakb(String nefudakb) {
        this.nefudakb = nefudakb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.nefudazeikb
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.nefudazeikb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getNefudazeikb() {
        return nefudazeikb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.nefudazeikb
     *
     * @param nefudazeikb the value for lb01_pt.lbt21_tana_meisai.nefudazeikb
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setNefudazeikb(String nefudazeikb) {
        this.nefudazeikb = nefudazeikb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.zeiritsu
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.zeiritsu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getZeiritsu() {
        return zeiritsu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.zeiritsu
     *
     * @param zeiritsu the value for lb01_pt.lbt21_tana_meisai.zeiritsu
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setZeiritsu(BigDecimal zeiritsu) {
        this.zeiritsu = zeiritsu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.shoyojikan
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.shoyojikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Short getShoyojikan() {
        return shoyojikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.shoyojikan
     *
     * @param shoyojikan the value for lb01_pt.lbt21_tana_meisai.shoyojikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShoyojikan(Short shoyojikan) {
        this.shoyojikan = shoyojikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvnum1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getRsvnum1() {
        return rsvnum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum1
     *
     * @param rsvnum1 the value for lb01_pt.lbt21_tana_meisai.rsvnum1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvnum1(BigDecimal rsvnum1) {
        this.rsvnum1 = rsvnum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvnum2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getRsvnum2() {
        return rsvnum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum2
     *
     * @param rsvnum2 the value for lb01_pt.lbt21_tana_meisai.rsvnum2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvnum2(BigDecimal rsvnum2) {
        this.rsvnum2 = rsvnum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum3
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvnum3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getRsvnum3() {
        return rsvnum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum3
     *
     * @param rsvnum3 the value for lb01_pt.lbt21_tana_meisai.rsvnum3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvnum3(BigDecimal rsvnum3) {
        this.rsvnum3 = rsvnum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum4
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvnum4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getRsvnum4() {
        return rsvnum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum4
     *
     * @param rsvnum4 the value for lb01_pt.lbt21_tana_meisai.rsvnum4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvnum4(BigDecimal rsvnum4) {
        this.rsvnum4 = rsvnum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum5
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvnum5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public BigDecimal getRsvnum5() {
        return rsvnum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvnum5
     *
     * @param rsvnum5 the value for lb01_pt.lbt21_tana_meisai.rsvnum5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvnum5(BigDecimal rsvnum5) {
        this.rsvnum5 = rsvnum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvkbn1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRsvkbn1() {
        return rsvkbn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn1
     *
     * @param rsvkbn1 the value for lb01_pt.lbt21_tana_meisai.rsvkbn1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvkbn1(String rsvkbn1) {
        this.rsvkbn1 = rsvkbn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvkbn2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRsvkbn2() {
        return rsvkbn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn2
     *
     * @param rsvkbn2 the value for lb01_pt.lbt21_tana_meisai.rsvkbn2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvkbn2(String rsvkbn2) {
        this.rsvkbn2 = rsvkbn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn3
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvkbn3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRsvkbn3() {
        return rsvkbn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn3
     *
     * @param rsvkbn3 the value for lb01_pt.lbt21_tana_meisai.rsvkbn3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvkbn3(String rsvkbn3) {
        this.rsvkbn3 = rsvkbn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn4
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvkbn4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRsvkbn4() {
        return rsvkbn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn4
     *
     * @param rsvkbn4 the value for lb01_pt.lbt21_tana_meisai.rsvkbn4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvkbn4(String rsvkbn4) {
        this.rsvkbn4 = rsvkbn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn5
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.rsvkbn5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getRsvkbn5() {
        return rsvkbn5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.rsvkbn5
     *
     * @param rsvkbn5 the value for lb01_pt.lbt21_tana_meisai.rsvkbn5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setRsvkbn5(String rsvkbn5) {
        this.rsvkbn5 = rsvkbn5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.kakuteiflg
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.kakuteiflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getKakuteiflg() {
        return kakuteiflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.kakuteiflg
     *
     * @param kakuteiflg the value for lb01_pt.lbt21_tana_meisai.kakuteiflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setKakuteiflg(String kakuteiflg) {
        this.kakuteiflg = kakuteiflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.chohyono
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.chohyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getChohyono() {
        return chohyono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.chohyono
     *
     * @param chohyono the value for lb01_pt.lbt21_tana_meisai.chohyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setChohyono(String chohyono) {
        this.chohyono = chohyono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errgyono
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errgyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Short getErrgyono() {
        return errgyono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errgyono
     *
     * @param errgyono the value for lb01_pt.lbt21_tana_meisai.errgyono
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrgyono(Short errgyono) {
        this.errgyono = errgyono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb1
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb1() {
        return errkb1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb1
     *
     * @param errkb1 the value for lb01_pt.lbt21_tana_meisai.errkb1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb1(String errkb1) {
        this.errkb1 = errkb1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb2
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb2() {
        return errkb2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb2
     *
     * @param errkb2 the value for lb01_pt.lbt21_tana_meisai.errkb2
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb2(String errkb2) {
        this.errkb2 = errkb2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb3
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb3() {
        return errkb3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb3
     *
     * @param errkb3 the value for lb01_pt.lbt21_tana_meisai.errkb3
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb3(String errkb3) {
        this.errkb3 = errkb3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb4
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb4() {
        return errkb4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb4
     *
     * @param errkb4 the value for lb01_pt.lbt21_tana_meisai.errkb4
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb4(String errkb4) {
        this.errkb4 = errkb4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb5
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb5() {
        return errkb5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb5
     *
     * @param errkb5 the value for lb01_pt.lbt21_tana_meisai.errkb5
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb5(String errkb5) {
        this.errkb5 = errkb5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb6
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb6
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb6() {
        return errkb6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb6
     *
     * @param errkb6 the value for lb01_pt.lbt21_tana_meisai.errkb6
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb6(String errkb6) {
        this.errkb6 = errkb6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb7
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb7
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb7() {
        return errkb7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb7
     *
     * @param errkb7 the value for lb01_pt.lbt21_tana_meisai.errkb7
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb7(String errkb7) {
        this.errkb7 = errkb7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb8
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb8
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb8() {
        return errkb8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb8
     *
     * @param errkb8 the value for lb01_pt.lbt21_tana_meisai.errkb8
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb8(String errkb8) {
        this.errkb8 = errkb8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb9
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb9
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb9() {
        return errkb9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb9
     *
     * @param errkb9 the value for lb01_pt.lbt21_tana_meisai.errkb9
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb9(String errkb9) {
        this.errkb9 = errkb9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb10
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb10
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb10() {
        return errkb10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb10
     *
     * @param errkb10 the value for lb01_pt.lbt21_tana_meisai.errkb10
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb10(String errkb10) {
        this.errkb10 = errkb10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb11
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb11
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb11() {
        return errkb11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb11
     *
     * @param errkb11 the value for lb01_pt.lbt21_tana_meisai.errkb11
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb11(String errkb11) {
        this.errkb11 = errkb11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb12
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb12
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb12() {
        return errkb12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb12
     *
     * @param errkb12 the value for lb01_pt.lbt21_tana_meisai.errkb12
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb12(String errkb12) {
        this.errkb12 = errkb12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb13
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb13() {
        return errkb13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb13
     *
     * @param errkb13 the value for lb01_pt.lbt21_tana_meisai.errkb13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb13(String errkb13) {
        this.errkb13 = errkb13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb14
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb14
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb14() {
        return errkb14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb14
     *
     * @param errkb14 the value for lb01_pt.lbt21_tana_meisai.errkb14
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb14(String errkb14) {
        this.errkb14 = errkb14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb15
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb15
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb15() {
        return errkb15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb15
     *
     * @param errkb15 the value for lb01_pt.lbt21_tana_meisai.errkb15
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb15(String errkb15) {
        this.errkb15 = errkb15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb16
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb16
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb16() {
        return errkb16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb16
     *
     * @param errkb16 the value for lb01_pt.lbt21_tana_meisai.errkb16
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb16(String errkb16) {
        this.errkb16 = errkb16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb17
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb17
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb17() {
        return errkb17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb17
     *
     * @param errkb17 the value for lb01_pt.lbt21_tana_meisai.errkb17
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb17(String errkb17) {
        this.errkb17 = errkb17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb18
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb18
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb18() {
        return errkb18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb18
     *
     * @param errkb18 the value for lb01_pt.lbt21_tana_meisai.errkb18
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb18(String errkb18) {
        this.errkb18 = errkb18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb19
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb19
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb19() {
        return errkb19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb19
     *
     * @param errkb19 the value for lb01_pt.lbt21_tana_meisai.errkb19
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb19(String errkb19) {
        this.errkb19 = errkb19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb20
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb20
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb20() {
        return errkb20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb20
     *
     * @param errkb20 the value for lb01_pt.lbt21_tana_meisai.errkb20
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb20(String errkb20) {
        this.errkb20 = errkb20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb21
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb21
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb21() {
        return errkb21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb21
     *
     * @param errkb21 the value for lb01_pt.lbt21_tana_meisai.errkb21
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb21(String errkb21) {
        this.errkb21 = errkb21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb22
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb22
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb22() {
        return errkb22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb22
     *
     * @param errkb22 the value for lb01_pt.lbt21_tana_meisai.errkb22
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb22(String errkb22) {
        this.errkb22 = errkb22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb23
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb23
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb23() {
        return errkb23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb23
     *
     * @param errkb23 the value for lb01_pt.lbt21_tana_meisai.errkb23
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb23(String errkb23) {
        this.errkb23 = errkb23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb24
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb24
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb24() {
        return errkb24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb24
     *
     * @param errkb24 the value for lb01_pt.lbt21_tana_meisai.errkb24
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb24(String errkb24) {
        this.errkb24 = errkb24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb25
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb25
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb25() {
        return errkb25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb25
     *
     * @param errkb25 the value for lb01_pt.lbt21_tana_meisai.errkb25
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb25(String errkb25) {
        this.errkb25 = errkb25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb26
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb26
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb26() {
        return errkb26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb26
     *
     * @param errkb26 the value for lb01_pt.lbt21_tana_meisai.errkb26
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb26(String errkb26) {
        this.errkb26 = errkb26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb27
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb27
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb27() {
        return errkb27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb27
     *
     * @param errkb27 the value for lb01_pt.lbt21_tana_meisai.errkb27
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb27(String errkb27) {
        this.errkb27 = errkb27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb28
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb28
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb28() {
        return errkb28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb28
     *
     * @param errkb28 the value for lb01_pt.lbt21_tana_meisai.errkb28
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb28(String errkb28) {
        this.errkb28 = errkb28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb29
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb29
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb29() {
        return errkb29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb29
     *
     * @param errkb29 the value for lb01_pt.lbt21_tana_meisai.errkb29
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb29(String errkb29) {
        this.errkb29 = errkb29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.errkb30
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.errkb30
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getErrkb30() {
        return errkb30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.errkb30
     *
     * @param errkb30 the value for lb01_pt.lbt21_tana_meisai.errkb30
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setErrkb30(String errkb30) {
        this.errkb30 = errkb30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.delflg
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.delflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.delflg
     *
     * @param delflg the value for lb01_pt.lbt21_tana_meisai.delflg
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setDelflg(String delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.deldte
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Date getDeldte() {
        return deldte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.deldte
     *
     * @param deldte the value for lb01_pt.lbt21_tana_meisai.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setDeldte(Date deldte) {
        this.deldte = deldte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.instdte
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Date getInstdte() {
        return instdte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.instdte
     *
     * @param instdte the value for lb01_pt.lbt21_tana_meisai.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setInstdte(Date instdte) {
        this.instdte = instdte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.instusrid
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getInstusrid() {
        return instusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.instusrid
     *
     * @param instusrid the value for lb01_pt.lbt21_tana_meisai.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setInstusrid(String instusrid) {
        this.instusrid = instusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.instprgid
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getInstprgid() {
        return instprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.instprgid
     *
     * @param instprgid the value for lb01_pt.lbt21_tana_meisai.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setInstprgid(String instprgid) {
        this.instprgid = instprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.insipaddr
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getInsipaddr() {
        return insipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.insipaddr
     *
     * @param insipaddr the value for lb01_pt.lbt21_tana_meisai.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setInsipaddr(String insipaddr) {
        this.insipaddr = insipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.upddte
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Date getUpddte() {
        return upddte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.upddte
     *
     * @param upddte the value for lb01_pt.lbt21_tana_meisai.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setUpddte(Date upddte) {
        this.upddte = upddte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.updusrid
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getUpdusrid() {
        return updusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.updusrid
     *
     * @param updusrid the value for lb01_pt.lbt21_tana_meisai.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setUpdusrid(String updusrid) {
        this.updusrid = updusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.updprgid
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getUpdprgid() {
        return updprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.updprgid
     *
     * @param updprgid the value for lb01_pt.lbt21_tana_meisai.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setUpdprgid(String updprgid) {
        this.updprgid = updprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt21_tana_meisai.updipaddr
     *
     * @return the value of lb01_pt.lbt21_tana_meisai.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getUpdipaddr() {
        return updipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt21_tana_meisai.updipaddr
     *
     * @param updipaddr the value for lb01_pt.lbt21_tana_meisai.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setUpdipaddr(String updipaddr) {
        this.updipaddr = updipaddr;
    }
}