package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt22TanaBaikan;
import com.feast.kanjo.entity.Lbt22TanaBaikanExample;
import com.feast.kanjo.entity.Lbt22TanaBaikanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt22TanaBaikanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbt22TanaBaikanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbt22TanaBaikanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Lbt22TanaBaikanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbt22TanaBaikan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbt22TanaBaikan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbt22TanaBaikan> selectByExample(Lbt22TanaBaikanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Lbt22TanaBaikan selectByPrimaryKey(Lbt22TanaBaikanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt22TanaBaikan record, @Param("example") Lbt22TanaBaikanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbt22TanaBaikan record, @Param("example") Lbt22TanaBaikanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt22TanaBaikan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt22_tana_baikan
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Lbt22TanaBaikan record);
}