package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt34ShohinY;
import com.feast.kanjo.entity.Lbt34ShohinYExample;
import com.feast.kanjo.entity.Lbt34ShohinYKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt34ShohinYMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int countByExample(Lbt34ShohinYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByExample(Lbt34ShohinYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByPrimaryKey(Lbt34ShohinYKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insert(Lbt34ShohinY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insertSelective(Lbt34ShohinY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    List<Lbt34ShohinY> selectByExample(Lbt34ShohinYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    Lbt34ShohinY selectByPrimaryKey(Lbt34ShohinYKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt34ShohinY record, @Param("example") Lbt34ShohinYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExample(@Param("record") Lbt34ShohinY record, @Param("example") Lbt34ShohinYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt34ShohinY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt34_shohin_y
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByPrimaryKey(Lbt34ShohinY record);
}