package com.feast.kanjo.entity;

public class Lbt34ShohinYKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer nendo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String sysgrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kgygrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tencd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tnpncd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt34_shohin_y.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shiirekbn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.nendo
     *
     * @return the value of lb01_pt.lbt34_shohin_y.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getNendo() {
        return nendo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.nendo
     *
     * @param nendo the value for lb01_pt.lbt34_shohin_y.nendo
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setNendo(Integer nendo) {
        this.nendo = nendo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.sysgrpcd
     *
     * @return the value of lb01_pt.lbt34_shohin_y.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getSysgrpcd() {
        return sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.sysgrpcd
     *
     * @param sysgrpcd the value for lb01_pt.lbt34_shohin_y.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSysgrpcd(String sysgrpcd) {
        this.sysgrpcd = sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.kgygrpcd
     *
     * @return the value of lb01_pt.lbt34_shohin_y.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKgygrpcd() {
        return kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.kgygrpcd
     *
     * @param kgygrpcd the value for lb01_pt.lbt34_shohin_y.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKgygrpcd(String kgygrpcd) {
        this.kgygrpcd = kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.tencd
     *
     * @return the value of lb01_pt.lbt34_shohin_y.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTencd() {
        return tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.tencd
     *
     * @param tencd the value for lb01_pt.lbt34_shohin_y.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTencd(String tencd) {
        this.tencd = tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.tnpncd1
     *
     * @return the value of lb01_pt.lbt34_shohin_y.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTnpncd1() {
        return tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.tnpncd1
     *
     * @param tnpncd1 the value for lb01_pt.lbt34_shohin_y.tnpncd1
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTnpncd1(String tnpncd1) {
        this.tnpncd1 = tnpncd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt34_shohin_y.shiirekbn
     *
     * @return the value of lb01_pt.lbt34_shohin_y.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShiirekbn() {
        return shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt34_shohin_y.shiirekbn
     *
     * @param shiirekbn the value for lb01_pt.lbt34_shohin_y.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShiirekbn(String shiirekbn) {
        this.shiirekbn = shiirekbn;
    }
}