package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt31ShohinD;
import com.feast.kanjo.entity.Lbt31ShohinDExample;
import com.feast.kanjo.entity.Lbt31ShohinDKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt31ShohinDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbt31ShohinDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbt31ShohinDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Lbt31ShohinDKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbt31ShohinD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbt31ShohinD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbt31ShohinD> selectByExample(Lbt31ShohinDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Lbt31ShohinD selectByPrimaryKey(Lbt31ShohinDKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt31ShohinD record, @Param("example") Lbt31ShohinDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbt31ShohinD record, @Param("example") Lbt31ShohinDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt31ShohinD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt31_shohin_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Lbt31ShohinD record);
}