package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt72TesuryoSumD;
import com.feast.kanjo.entity.Lbt72TesuryoSumDExample;
import com.feast.kanjo.entity.Lbt72TesuryoSumDKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt72TesuryoSumDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbt72TesuryoSumDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbt72TesuryoSumDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Lbt72TesuryoSumDKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbt72TesuryoSumD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbt72TesuryoSumD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbt72TesuryoSumD> selectByExample(Lbt72TesuryoSumDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Lbt72TesuryoSumD selectByPrimaryKey(Lbt72TesuryoSumDKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt72TesuryoSumD record, @Param("example") Lbt72TesuryoSumDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbt72TesuryoSumD record, @Param("example") Lbt72TesuryoSumDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt72TesuryoSumD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt72_tesuryo_sum_d
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Lbt72TesuryoSumD record);
}