package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt79Gaisyopos;
import com.feast.kanjo.entity.Lbt79GaisyoposExample;
import com.feast.kanjo.entity.Lbt79GaisyoposKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt79GaisyoposMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbt79GaisyoposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbt79GaisyoposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Lbt79GaisyoposKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbt79Gaisyopos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbt79Gaisyopos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbt79Gaisyopos> selectByExample(Lbt79GaisyoposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Lbt79Gaisyopos selectByPrimaryKey(Lbt79GaisyoposKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt79Gaisyopos record, @Param("example") Lbt79GaisyoposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbt79Gaisyopos record, @Param("example") Lbt79GaisyoposExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Lbt79Gaisyopos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt79_gaisyopos
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Lbt79Gaisyopos record);
}