package com.feast.kanjo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Lbt76EmSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Lbt76EmSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTotsugokubunIsNull() {
            addCriterion("totsugokubun is null");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunIsNotNull() {
            addCriterion("totsugokubun is not null");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunEqualTo(String value) {
            addCriterion("totsugokubun =", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunNotEqualTo(String value) {
            addCriterion("totsugokubun <>", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunGreaterThan(String value) {
            addCriterion("totsugokubun >", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunGreaterThanOrEqualTo(String value) {
            addCriterion("totsugokubun >=", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunLessThan(String value) {
            addCriterion("totsugokubun <", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunLessThanOrEqualTo(String value) {
            addCriterion("totsugokubun <=", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunLike(String value) {
            addCriterion("totsugokubun like", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunNotLike(String value) {
            addCriterion("totsugokubun not like", value, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunIn(List<String> values) {
            addCriterion("totsugokubun in", values, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunNotIn(List<String> values) {
            addCriterion("totsugokubun not in", values, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunBetween(String value1, String value2) {
            addCriterion("totsugokubun between", value1, value2, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugokubunNotBetween(String value1, String value2) {
            addCriterion("totsugokubun not between", value1, value2, "totsugokubun");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdIsNull() {
            addCriterion("totsugoymd is null");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdIsNotNull() {
            addCriterion("totsugoymd is not null");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdEqualTo(Date value) {
            addCriterion("totsugoymd =", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdNotEqualTo(Date value) {
            addCriterion("totsugoymd <>", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdGreaterThan(Date value) {
            addCriterion("totsugoymd >", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdGreaterThanOrEqualTo(Date value) {
            addCriterion("totsugoymd >=", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdLessThan(Date value) {
            addCriterion("totsugoymd <", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdLessThanOrEqualTo(Date value) {
            addCriterion("totsugoymd <=", value, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdIn(List<Date> values) {
            addCriterion("totsugoymd in", values, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdNotIn(List<Date> values) {
            addCriterion("totsugoymd not in", values, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdBetween(Date value1, Date value2) {
            addCriterion("totsugoymd between", value1, value2, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andTotsugoymdNotBetween(Date value1, Date value2) {
            addCriterion("totsugoymd not between", value1, value2, "totsugoymd");
            return (Criteria) this;
        }

        public Criteria andCdIsNull() {
            addCriterion("cd is null");
            return (Criteria) this;
        }

        public Criteria andCdIsNotNull() {
            addCriterion("cd is not null");
            return (Criteria) this;
        }

        public Criteria andCdEqualTo(String value) {
            addCriterion("cd =", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotEqualTo(String value) {
            addCriterion("cd <>", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThan(String value) {
            addCriterion("cd >", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThanOrEqualTo(String value) {
            addCriterion("cd >=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThan(String value) {
            addCriterion("cd <", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThanOrEqualTo(String value) {
            addCriterion("cd <=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLike(String value) {
            addCriterion("cd like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotLike(String value) {
            addCriterion("cd not like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdIn(List<String> values) {
            addCriterion("cd in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotIn(List<String> values) {
            addCriterion("cd not in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdBetween(String value1, String value2) {
            addCriterion("cd between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotBetween(String value1, String value2) {
            addCriterion("cd not between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andKensu1IsNull() {
            addCriterion("kensu1 is null");
            return (Criteria) this;
        }

        public Criteria andKensu1IsNotNull() {
            addCriterion("kensu1 is not null");
            return (Criteria) this;
        }

        public Criteria andKensu1EqualTo(Integer value) {
            addCriterion("kensu1 =", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1NotEqualTo(Integer value) {
            addCriterion("kensu1 <>", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1GreaterThan(Integer value) {
            addCriterion("kensu1 >", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1GreaterThanOrEqualTo(Integer value) {
            addCriterion("kensu1 >=", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1LessThan(Integer value) {
            addCriterion("kensu1 <", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1LessThanOrEqualTo(Integer value) {
            addCriterion("kensu1 <=", value, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1In(List<Integer> values) {
            addCriterion("kensu1 in", values, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1NotIn(List<Integer> values) {
            addCriterion("kensu1 not in", values, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1Between(Integer value1, Integer value2) {
            addCriterion("kensu1 between", value1, value2, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu1NotBetween(Integer value1, Integer value2) {
            addCriterion("kensu1 not between", value1, value2, "kensu1");
            return (Criteria) this;
        }

        public Criteria andKensu2IsNull() {
            addCriterion("kensu2 is null");
            return (Criteria) this;
        }

        public Criteria andKensu2IsNotNull() {
            addCriterion("kensu2 is not null");
            return (Criteria) this;
        }

        public Criteria andKensu2EqualTo(Integer value) {
            addCriterion("kensu2 =", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2NotEqualTo(Integer value) {
            addCriterion("kensu2 <>", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2GreaterThan(Integer value) {
            addCriterion("kensu2 >", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2GreaterThanOrEqualTo(Integer value) {
            addCriterion("kensu2 >=", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2LessThan(Integer value) {
            addCriterion("kensu2 <", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2LessThanOrEqualTo(Integer value) {
            addCriterion("kensu2 <=", value, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2In(List<Integer> values) {
            addCriterion("kensu2 in", values, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2NotIn(List<Integer> values) {
            addCriterion("kensu2 not in", values, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2Between(Integer value1, Integer value2) {
            addCriterion("kensu2 between", value1, value2, "kensu2");
            return (Criteria) this;
        }

        public Criteria andKensu2NotBetween(Integer value1, Integer value2) {
            addCriterion("kensu2 not between", value1, value2, "kensu2");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeldteIsNull() {
            addCriterion("deldte is null");
            return (Criteria) this;
        }

        public Criteria andDeldteIsNotNull() {
            addCriterion("deldte is not null");
            return (Criteria) this;
        }

        public Criteria andDeldteEqualTo(Date value) {
            addCriterion("deldte =", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotEqualTo(Date value) {
            addCriterion("deldte <>", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteGreaterThan(Date value) {
            addCriterion("deldte >", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteGreaterThanOrEqualTo(Date value) {
            addCriterion("deldte >=", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteLessThan(Date value) {
            addCriterion("deldte <", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteLessThanOrEqualTo(Date value) {
            addCriterion("deldte <=", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteIn(List<Date> values) {
            addCriterion("deldte in", values, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotIn(List<Date> values) {
            addCriterion("deldte not in", values, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteBetween(Date value1, Date value2) {
            addCriterion("deldte between", value1, value2, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotBetween(Date value1, Date value2) {
            addCriterion("deldte not between", value1, value2, "deldte");
            return (Criteria) this;
        }

        public Criteria andInstdteIsNull() {
            addCriterion("instdte is null");
            return (Criteria) this;
        }

        public Criteria andInstdteIsNotNull() {
            addCriterion("instdte is not null");
            return (Criteria) this;
        }

        public Criteria andInstdteEqualTo(Date value) {
            addCriterion("instdte =", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotEqualTo(Date value) {
            addCriterion("instdte <>", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteGreaterThan(Date value) {
            addCriterion("instdte >", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteGreaterThanOrEqualTo(Date value) {
            addCriterion("instdte >=", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteLessThan(Date value) {
            addCriterion("instdte <", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteLessThanOrEqualTo(Date value) {
            addCriterion("instdte <=", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteIn(List<Date> values) {
            addCriterion("instdte in", values, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotIn(List<Date> values) {
            addCriterion("instdte not in", values, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteBetween(Date value1, Date value2) {
            addCriterion("instdte between", value1, value2, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotBetween(Date value1, Date value2) {
            addCriterion("instdte not between", value1, value2, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstusridIsNull() {
            addCriterion("instusrid is null");
            return (Criteria) this;
        }

        public Criteria andInstusridIsNotNull() {
            addCriterion("instusrid is not null");
            return (Criteria) this;
        }

        public Criteria andInstusridEqualTo(String value) {
            addCriterion("instusrid =", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotEqualTo(String value) {
            addCriterion("instusrid <>", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridGreaterThan(String value) {
            addCriterion("instusrid >", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridGreaterThanOrEqualTo(String value) {
            addCriterion("instusrid >=", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLessThan(String value) {
            addCriterion("instusrid <", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLessThanOrEqualTo(String value) {
            addCriterion("instusrid <=", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLike(String value) {
            addCriterion("instusrid like", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotLike(String value) {
            addCriterion("instusrid not like", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridIn(List<String> values) {
            addCriterion("instusrid in", values, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotIn(List<String> values) {
            addCriterion("instusrid not in", values, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridBetween(String value1, String value2) {
            addCriterion("instusrid between", value1, value2, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotBetween(String value1, String value2) {
            addCriterion("instusrid not between", value1, value2, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstprgidIsNull() {
            addCriterion("instprgid is null");
            return (Criteria) this;
        }

        public Criteria andInstprgidIsNotNull() {
            addCriterion("instprgid is not null");
            return (Criteria) this;
        }

        public Criteria andInstprgidEqualTo(String value) {
            addCriterion("instprgid =", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotEqualTo(String value) {
            addCriterion("instprgid <>", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidGreaterThan(String value) {
            addCriterion("instprgid >", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidGreaterThanOrEqualTo(String value) {
            addCriterion("instprgid >=", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLessThan(String value) {
            addCriterion("instprgid <", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLessThanOrEqualTo(String value) {
            addCriterion("instprgid <=", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLike(String value) {
            addCriterion("instprgid like", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotLike(String value) {
            addCriterion("instprgid not like", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidIn(List<String> values) {
            addCriterion("instprgid in", values, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotIn(List<String> values) {
            addCriterion("instprgid not in", values, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidBetween(String value1, String value2) {
            addCriterion("instprgid between", value1, value2, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotBetween(String value1, String value2) {
            addCriterion("instprgid not between", value1, value2, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIsNull() {
            addCriterion("insipaddr is null");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIsNotNull() {
            addCriterion("insipaddr is not null");
            return (Criteria) this;
        }

        public Criteria andInsipaddrEqualTo(String value) {
            addCriterion("insipaddr =", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotEqualTo(String value) {
            addCriterion("insipaddr <>", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrGreaterThan(String value) {
            addCriterion("insipaddr >", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrGreaterThanOrEqualTo(String value) {
            addCriterion("insipaddr >=", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLessThan(String value) {
            addCriterion("insipaddr <", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLessThanOrEqualTo(String value) {
            addCriterion("insipaddr <=", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLike(String value) {
            addCriterion("insipaddr like", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotLike(String value) {
            addCriterion("insipaddr not like", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIn(List<String> values) {
            addCriterion("insipaddr in", values, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotIn(List<String> values) {
            addCriterion("insipaddr not in", values, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrBetween(String value1, String value2) {
            addCriterion("insipaddr between", value1, value2, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotBetween(String value1, String value2) {
            addCriterion("insipaddr not between", value1, value2, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andUpddteIsNull() {
            addCriterion("upddte is null");
            return (Criteria) this;
        }

        public Criteria andUpddteIsNotNull() {
            addCriterion("upddte is not null");
            return (Criteria) this;
        }

        public Criteria andUpddteEqualTo(Date value) {
            addCriterion("upddte =", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotEqualTo(Date value) {
            addCriterion("upddte <>", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteGreaterThan(Date value) {
            addCriterion("upddte >", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteGreaterThanOrEqualTo(Date value) {
            addCriterion("upddte >=", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteLessThan(Date value) {
            addCriterion("upddte <", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteLessThanOrEqualTo(Date value) {
            addCriterion("upddte <=", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteIn(List<Date> values) {
            addCriterion("upddte in", values, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotIn(List<Date> values) {
            addCriterion("upddte not in", values, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteBetween(Date value1, Date value2) {
            addCriterion("upddte between", value1, value2, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotBetween(Date value1, Date value2) {
            addCriterion("upddte not between", value1, value2, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpdusridIsNull() {
            addCriterion("updusrid is null");
            return (Criteria) this;
        }

        public Criteria andUpdusridIsNotNull() {
            addCriterion("updusrid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdusridEqualTo(String value) {
            addCriterion("updusrid =", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotEqualTo(String value) {
            addCriterion("updusrid <>", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridGreaterThan(String value) {
            addCriterion("updusrid >", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridGreaterThanOrEqualTo(String value) {
            addCriterion("updusrid >=", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLessThan(String value) {
            addCriterion("updusrid <", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLessThanOrEqualTo(String value) {
            addCriterion("updusrid <=", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLike(String value) {
            addCriterion("updusrid like", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotLike(String value) {
            addCriterion("updusrid not like", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridIn(List<String> values) {
            addCriterion("updusrid in", values, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotIn(List<String> values) {
            addCriterion("updusrid not in", values, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridBetween(String value1, String value2) {
            addCriterion("updusrid between", value1, value2, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotBetween(String value1, String value2) {
            addCriterion("updusrid not between", value1, value2, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIsNull() {
            addCriterion("updprgid is null");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIsNotNull() {
            addCriterion("updprgid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdprgidEqualTo(String value) {
            addCriterion("updprgid =", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotEqualTo(String value) {
            addCriterion("updprgid <>", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidGreaterThan(String value) {
            addCriterion("updprgid >", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidGreaterThanOrEqualTo(String value) {
            addCriterion("updprgid >=", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLessThan(String value) {
            addCriterion("updprgid <", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLessThanOrEqualTo(String value) {
            addCriterion("updprgid <=", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLike(String value) {
            addCriterion("updprgid like", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotLike(String value) {
            addCriterion("updprgid not like", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIn(List<String> values) {
            addCriterion("updprgid in", values, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotIn(List<String> values) {
            addCriterion("updprgid not in", values, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidBetween(String value1, String value2) {
            addCriterion("updprgid between", value1, value2, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotBetween(String value1, String value2) {
            addCriterion("updprgid not between", value1, value2, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIsNull() {
            addCriterion("updipaddr is null");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIsNotNull() {
            addCriterion("updipaddr is not null");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrEqualTo(String value) {
            addCriterion("updipaddr =", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotEqualTo(String value) {
            addCriterion("updipaddr <>", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrGreaterThan(String value) {
            addCriterion("updipaddr >", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrGreaterThanOrEqualTo(String value) {
            addCriterion("updipaddr >=", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLessThan(String value) {
            addCriterion("updipaddr <", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLessThanOrEqualTo(String value) {
            addCriterion("updipaddr <=", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLike(String value) {
            addCriterion("updipaddr like", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotLike(String value) {
            addCriterion("updipaddr not like", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIn(List<String> values) {
            addCriterion("updipaddr in", values, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotIn(List<String> values) {
            addCriterion("updipaddr not in", values, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrBetween(String value1, String value2) {
            addCriterion("updipaddr between", value1, value2, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotBetween(String value1, String value2) {
            addCriterion("updipaddr not between", value1, value2, "updipaddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 22 17:43:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lbt76_em_summary
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}