package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt80Tesuryomeisai;
import com.feast.kanjo.entity.Lbt80TesuryomeisaiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt80TesuryomeisaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int countByExample(Lbt80TesuryomeisaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByExample(Lbt80TesuryomeisaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insert(Lbt80Tesuryomeisai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insertSelective(Lbt80Tesuryomeisai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    List<Lbt80Tesuryomeisai> selectByExample(Lbt80TesuryomeisaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt80Tesuryomeisai record, @Param("example") Lbt80TesuryomeisaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt80_tesuryomeisai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExample(@Param("record") Lbt80Tesuryomeisai record, @Param("example") Lbt80TesuryomeisaiExample example);
}