package com.feast.kanjo.entity;

public class Lbt84ZennenJissekiPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.sakusei_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer sakuseiYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.zennen_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer zennenYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tencd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String bucd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kacd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kakaricd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String unitcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String hinban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.jikantai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String jikantai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt84_zennen_jisseki_pkey.basho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String basho;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.sakusei_ymd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.sakusei_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getSakuseiYmd() {
        return sakuseiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.sakusei_ymd
     *
     * @param sakuseiYmd the value for lb01_pt.lbt84_zennen_jisseki_pkey.sakusei_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSakuseiYmd(Integer sakuseiYmd) {
        this.sakuseiYmd = sakuseiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.zennen_ymd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.zennen_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getZennenYmd() {
        return zennenYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.zennen_ymd
     *
     * @param zennenYmd the value for lb01_pt.lbt84_zennen_jisseki_pkey.zennen_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setZennenYmd(Integer zennenYmd) {
        this.zennenYmd = zennenYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.tencd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTencd() {
        return tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.tencd
     *
     * @param tencd the value for lb01_pt.lbt84_zennen_jisseki_pkey.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTencd(String tencd) {
        this.tencd = tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.bucd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getBucd() {
        return bucd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.bucd
     *
     * @param bucd the value for lb01_pt.lbt84_zennen_jisseki_pkey.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setBucd(String bucd) {
        this.bucd = bucd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.kacd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKacd() {
        return kacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.kacd
     *
     * @param kacd the value for lb01_pt.lbt84_zennen_jisseki_pkey.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKacd(String kacd) {
        this.kacd = kacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.kakaricd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKakaricd() {
        return kakaricd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.kakaricd
     *
     * @param kakaricd the value for lb01_pt.lbt84_zennen_jisseki_pkey.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKakaricd(String kakaricd) {
        this.kakaricd = kakaricd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.unitcd
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUnitcd() {
        return unitcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.unitcd
     *
     * @param unitcd the value for lb01_pt.lbt84_zennen_jisseki_pkey.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUnitcd(String unitcd) {
        this.unitcd = unitcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.hinban
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getHinban() {
        return hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.hinban
     *
     * @param hinban the value for lb01_pt.lbt84_zennen_jisseki_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setHinban(String hinban) {
        this.hinban = hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.jikantai
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.jikantai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getJikantai() {
        return jikantai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.jikantai
     *
     * @param jikantai the value for lb01_pt.lbt84_zennen_jisseki_pkey.jikantai
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setJikantai(String jikantai) {
        this.jikantai = jikantai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.basho
     *
     * @return the value of lb01_pt.lbt84_zennen_jisseki_pkey.basho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getBasho() {
        return basho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt84_zennen_jisseki_pkey.basho
     *
     * @param basho the value for lb01_pt.lbt84_zennen_jisseki_pkey.basho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setBasho(String basho) {
        this.basho = basho;
    }
}