package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbt84ZennenJissekiPkey;
import com.feast.kanjo.entity.Lbt84ZennenJissekiPkeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbt84ZennenJissekiPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int countByExample(Lbt84ZennenJissekiPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int deleteByExample(Lbt84ZennenJissekiPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insert(Lbt84ZennenJissekiPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int insertSelective(Lbt84ZennenJissekiPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    List<Lbt84ZennenJissekiPkey> selectByExample(Lbt84ZennenJissekiPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbt84ZennenJissekiPkey record, @Param("example") Lbt84ZennenJissekiPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbt84_zennen_jisseki_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    int updateByExample(@Param("record") Lbt84ZennenJissekiPkey record, @Param("example") Lbt84ZennenJissekiPkeyExample example);
}