package com.feast.kanjo.entity;

import java.util.Date;

public class Lbt82KinkenSum extends Lbt82KinkenSumKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String bucd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kacd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kakaricd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String unitcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.torihikisakicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String torihikisakicd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String saijicd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kazeikbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kazeikbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String shiirekbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.torihikisakinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String torihikisakinm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.misenm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String misenm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.bunm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String bunm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kanm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kanm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kakarinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kakarinm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.unitnm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String unitnm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.hinbannm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String hinbannm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyou30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long kinkenriyou30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.kinkenriyousum_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer kinkenriyousumYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryo30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Long tesuryo30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryoshorihoho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String tesuryoshorihoho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.tesuryocalc_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Integer tesuryocalcYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Date deldte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Date instdte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String instusrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String instprgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String insipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Date upddte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String updusrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String updprgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbt82_kinken_sum.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String updipaddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.bucd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getBucd() {
        return bucd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.bucd
     *
     * @param bucd the value for lb01_pt.lbt82_kinken_sum.bucd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setBucd(String bucd) {
        this.bucd = bucd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kacd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKacd() {
        return kacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kacd
     *
     * @param kacd the value for lb01_pt.lbt82_kinken_sum.kacd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKacd(String kacd) {
        this.kacd = kacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kakaricd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKakaricd() {
        return kakaricd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kakaricd
     *
     * @param kakaricd the value for lb01_pt.lbt82_kinken_sum.kakaricd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKakaricd(String kakaricd) {
        this.kakaricd = kakaricd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.unitcd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUnitcd() {
        return unitcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.unitcd
     *
     * @param unitcd the value for lb01_pt.lbt82_kinken_sum.unitcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUnitcd(String unitcd) {
        this.unitcd = unitcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.torihikisakicd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.torihikisakicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTorihikisakicd() {
        return torihikisakicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.torihikisakicd
     *
     * @param torihikisakicd the value for lb01_pt.lbt82_kinken_sum.torihikisakicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTorihikisakicd(String torihikisakicd) {
        this.torihikisakicd = torihikisakicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.saijicd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getSaijicd() {
        return saijicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.saijicd
     *
     * @param saijicd the value for lb01_pt.lbt82_kinken_sum.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setSaijicd(String saijicd) {
        this.saijicd = saijicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kazeikbn
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kazeikbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKazeikbn() {
        return kazeikbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kazeikbn
     *
     * @param kazeikbn the value for lb01_pt.lbt82_kinken_sum.kazeikbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKazeikbn(String kazeikbn) {
        this.kazeikbn = kazeikbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.shiirekbn
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getShiirekbn() {
        return shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.shiirekbn
     *
     * @param shiirekbn the value for lb01_pt.lbt82_kinken_sum.shiirekbn
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setShiirekbn(String shiirekbn) {
        this.shiirekbn = shiirekbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.torihikisakinm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.torihikisakinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTorihikisakinm() {
        return torihikisakinm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.torihikisakinm
     *
     * @param torihikisakinm the value for lb01_pt.lbt82_kinken_sum.torihikisakinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTorihikisakinm(String torihikisakinm) {
        this.torihikisakinm = torihikisakinm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.misenm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.misenm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getMisenm() {
        return misenm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.misenm
     *
     * @param misenm the value for lb01_pt.lbt82_kinken_sum.misenm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setMisenm(String misenm) {
        this.misenm = misenm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.bunm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.bunm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getBunm() {
        return bunm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.bunm
     *
     * @param bunm the value for lb01_pt.lbt82_kinken_sum.bunm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setBunm(String bunm) {
        this.bunm = bunm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kanm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kanm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKanm() {
        return kanm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kanm
     *
     * @param kanm the value for lb01_pt.lbt82_kinken_sum.kanm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKanm(String kanm) {
        this.kanm = kanm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kakarinm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kakarinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKakarinm() {
        return kakarinm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kakarinm
     *
     * @param kakarinm the value for lb01_pt.lbt82_kinken_sum.kakarinm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKakarinm(String kakarinm) {
        this.kakarinm = kakarinm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.unitnm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.unitnm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUnitnm() {
        return unitnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.unitnm
     *
     * @param unitnm the value for lb01_pt.lbt82_kinken_sum.unitnm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUnitnm(String unitnm) {
        this.unitnm = unitnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.hinbannm
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.hinbannm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getHinbannm() {
        return hinbannm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.hinbannm
     *
     * @param hinbannm the value for lb01_pt.lbt82_kinken_sum.hinbannm
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setHinbannm(String hinbannm) {
        this.hinbannm = hinbannm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou01
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou01() {
        return kinkenriyou01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou01
     *
     * @param kinkenriyou01 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou01(Long kinkenriyou01) {
        this.kinkenriyou01 = kinkenriyou01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou02
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou02() {
        return kinkenriyou02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou02
     *
     * @param kinkenriyou02 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou02(Long kinkenriyou02) {
        this.kinkenriyou02 = kinkenriyou02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou03
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou03() {
        return kinkenriyou03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou03
     *
     * @param kinkenriyou03 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou03(Long kinkenriyou03) {
        this.kinkenriyou03 = kinkenriyou03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou04
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou04() {
        return kinkenriyou04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou04
     *
     * @param kinkenriyou04 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou04(Long kinkenriyou04) {
        this.kinkenriyou04 = kinkenriyou04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou05
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou05() {
        return kinkenriyou05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou05
     *
     * @param kinkenriyou05 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou05(Long kinkenriyou05) {
        this.kinkenriyou05 = kinkenriyou05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou06
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou06() {
        return kinkenriyou06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou06
     *
     * @param kinkenriyou06 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou06(Long kinkenriyou06) {
        this.kinkenriyou06 = kinkenriyou06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou07
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou07() {
        return kinkenriyou07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou07
     *
     * @param kinkenriyou07 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou07(Long kinkenriyou07) {
        this.kinkenriyou07 = kinkenriyou07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou08
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou08() {
        return kinkenriyou08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou08
     *
     * @param kinkenriyou08 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou08(Long kinkenriyou08) {
        this.kinkenriyou08 = kinkenriyou08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou09
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou09() {
        return kinkenriyou09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou09
     *
     * @param kinkenriyou09 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou09(Long kinkenriyou09) {
        this.kinkenriyou09 = kinkenriyou09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou10
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou10() {
        return kinkenriyou10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou10
     *
     * @param kinkenriyou10 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou10(Long kinkenriyou10) {
        this.kinkenriyou10 = kinkenriyou10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou11
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou11() {
        return kinkenriyou11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou11
     *
     * @param kinkenriyou11 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou11(Long kinkenriyou11) {
        this.kinkenriyou11 = kinkenriyou11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou12
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou12() {
        return kinkenriyou12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou12
     *
     * @param kinkenriyou12 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou12(Long kinkenriyou12) {
        this.kinkenriyou12 = kinkenriyou12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou13
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou13() {
        return kinkenriyou13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou13
     *
     * @param kinkenriyou13 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou13(Long kinkenriyou13) {
        this.kinkenriyou13 = kinkenriyou13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou14
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou14() {
        return kinkenriyou14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou14
     *
     * @param kinkenriyou14 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou14(Long kinkenriyou14) {
        this.kinkenriyou14 = kinkenriyou14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou15
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou15() {
        return kinkenriyou15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou15
     *
     * @param kinkenriyou15 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou15(Long kinkenriyou15) {
        this.kinkenriyou15 = kinkenriyou15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou16
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou16() {
        return kinkenriyou16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou16
     *
     * @param kinkenriyou16 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou16(Long kinkenriyou16) {
        this.kinkenriyou16 = kinkenriyou16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou17
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou17() {
        return kinkenriyou17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou17
     *
     * @param kinkenriyou17 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou17(Long kinkenriyou17) {
        this.kinkenriyou17 = kinkenriyou17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou18
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou18() {
        return kinkenriyou18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou18
     *
     * @param kinkenriyou18 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou18(Long kinkenriyou18) {
        this.kinkenriyou18 = kinkenriyou18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou19
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou19() {
        return kinkenriyou19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou19
     *
     * @param kinkenriyou19 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou19(Long kinkenriyou19) {
        this.kinkenriyou19 = kinkenriyou19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou20
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou20() {
        return kinkenriyou20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou20
     *
     * @param kinkenriyou20 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou20(Long kinkenriyou20) {
        this.kinkenriyou20 = kinkenriyou20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou21
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou21() {
        return kinkenriyou21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou21
     *
     * @param kinkenriyou21 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou21(Long kinkenriyou21) {
        this.kinkenriyou21 = kinkenriyou21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou22
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou22() {
        return kinkenriyou22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou22
     *
     * @param kinkenriyou22 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou22(Long kinkenriyou22) {
        this.kinkenriyou22 = kinkenriyou22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou23
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou23() {
        return kinkenriyou23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou23
     *
     * @param kinkenriyou23 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou23(Long kinkenriyou23) {
        this.kinkenriyou23 = kinkenriyou23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou24
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou24() {
        return kinkenriyou24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou24
     *
     * @param kinkenriyou24 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou24(Long kinkenriyou24) {
        this.kinkenriyou24 = kinkenriyou24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou25
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou25() {
        return kinkenriyou25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou25
     *
     * @param kinkenriyou25 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou25(Long kinkenriyou25) {
        this.kinkenriyou25 = kinkenriyou25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou26
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou26() {
        return kinkenriyou26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou26
     *
     * @param kinkenriyou26 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou26(Long kinkenriyou26) {
        this.kinkenriyou26 = kinkenriyou26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou27
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou27() {
        return kinkenriyou27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou27
     *
     * @param kinkenriyou27 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou27(Long kinkenriyou27) {
        this.kinkenriyou27 = kinkenriyou27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou28
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou28() {
        return kinkenriyou28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou28
     *
     * @param kinkenriyou28 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou28(Long kinkenriyou28) {
        this.kinkenriyou28 = kinkenriyou28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou29
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou29() {
        return kinkenriyou29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou29
     *
     * @param kinkenriyou29 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou29(Long kinkenriyou29) {
        this.kinkenriyou29 = kinkenriyou29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou30
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyou30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getKinkenriyou30() {
        return kinkenriyou30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyou30
     *
     * @param kinkenriyou30 the value for lb01_pt.lbt82_kinken_sum.kinkenriyou30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyou30(Long kinkenriyou30) {
        this.kinkenriyou30 = kinkenriyou30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyousum_ymd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.kinkenriyousum_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getKinkenriyousumYmd() {
        return kinkenriyousumYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.kinkenriyousum_ymd
     *
     * @param kinkenriyousumYmd the value for lb01_pt.lbt82_kinken_sum.kinkenriyousum_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKinkenriyousumYmd(Integer kinkenriyousumYmd) {
        this.kinkenriyousumYmd = kinkenriyousumYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo01
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo01() {
        return tesuryo01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo01
     *
     * @param tesuryo01 the value for lb01_pt.lbt82_kinken_sum.tesuryo01
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo01(Long tesuryo01) {
        this.tesuryo01 = tesuryo01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo02
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo02() {
        return tesuryo02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo02
     *
     * @param tesuryo02 the value for lb01_pt.lbt82_kinken_sum.tesuryo02
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo02(Long tesuryo02) {
        this.tesuryo02 = tesuryo02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo03
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo03() {
        return tesuryo03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo03
     *
     * @param tesuryo03 the value for lb01_pt.lbt82_kinken_sum.tesuryo03
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo03(Long tesuryo03) {
        this.tesuryo03 = tesuryo03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo04
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo04() {
        return tesuryo04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo04
     *
     * @param tesuryo04 the value for lb01_pt.lbt82_kinken_sum.tesuryo04
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo04(Long tesuryo04) {
        this.tesuryo04 = tesuryo04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo05
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo05() {
        return tesuryo05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo05
     *
     * @param tesuryo05 the value for lb01_pt.lbt82_kinken_sum.tesuryo05
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo05(Long tesuryo05) {
        this.tesuryo05 = tesuryo05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo06
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo06() {
        return tesuryo06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo06
     *
     * @param tesuryo06 the value for lb01_pt.lbt82_kinken_sum.tesuryo06
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo06(Long tesuryo06) {
        this.tesuryo06 = tesuryo06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo07
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo07() {
        return tesuryo07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo07
     *
     * @param tesuryo07 the value for lb01_pt.lbt82_kinken_sum.tesuryo07
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo07(Long tesuryo07) {
        this.tesuryo07 = tesuryo07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo08
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo08() {
        return tesuryo08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo08
     *
     * @param tesuryo08 the value for lb01_pt.lbt82_kinken_sum.tesuryo08
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo08(Long tesuryo08) {
        this.tesuryo08 = tesuryo08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo09
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo09() {
        return tesuryo09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo09
     *
     * @param tesuryo09 the value for lb01_pt.lbt82_kinken_sum.tesuryo09
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo09(Long tesuryo09) {
        this.tesuryo09 = tesuryo09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo10
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo10() {
        return tesuryo10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo10
     *
     * @param tesuryo10 the value for lb01_pt.lbt82_kinken_sum.tesuryo10
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo10(Long tesuryo10) {
        this.tesuryo10 = tesuryo10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo11
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo11() {
        return tesuryo11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo11
     *
     * @param tesuryo11 the value for lb01_pt.lbt82_kinken_sum.tesuryo11
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo11(Long tesuryo11) {
        this.tesuryo11 = tesuryo11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo12
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo12() {
        return tesuryo12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo12
     *
     * @param tesuryo12 the value for lb01_pt.lbt82_kinken_sum.tesuryo12
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo12(Long tesuryo12) {
        this.tesuryo12 = tesuryo12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo13
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo13() {
        return tesuryo13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo13
     *
     * @param tesuryo13 the value for lb01_pt.lbt82_kinken_sum.tesuryo13
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo13(Long tesuryo13) {
        this.tesuryo13 = tesuryo13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo14
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo14() {
        return tesuryo14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo14
     *
     * @param tesuryo14 the value for lb01_pt.lbt82_kinken_sum.tesuryo14
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo14(Long tesuryo14) {
        this.tesuryo14 = tesuryo14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo15
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo15() {
        return tesuryo15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo15
     *
     * @param tesuryo15 the value for lb01_pt.lbt82_kinken_sum.tesuryo15
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo15(Long tesuryo15) {
        this.tesuryo15 = tesuryo15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo16
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo16() {
        return tesuryo16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo16
     *
     * @param tesuryo16 the value for lb01_pt.lbt82_kinken_sum.tesuryo16
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo16(Long tesuryo16) {
        this.tesuryo16 = tesuryo16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo17
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo17() {
        return tesuryo17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo17
     *
     * @param tesuryo17 the value for lb01_pt.lbt82_kinken_sum.tesuryo17
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo17(Long tesuryo17) {
        this.tesuryo17 = tesuryo17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo18
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo18() {
        return tesuryo18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo18
     *
     * @param tesuryo18 the value for lb01_pt.lbt82_kinken_sum.tesuryo18
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo18(Long tesuryo18) {
        this.tesuryo18 = tesuryo18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo19
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo19() {
        return tesuryo19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo19
     *
     * @param tesuryo19 the value for lb01_pt.lbt82_kinken_sum.tesuryo19
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo19(Long tesuryo19) {
        this.tesuryo19 = tesuryo19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo20
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo20() {
        return tesuryo20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo20
     *
     * @param tesuryo20 the value for lb01_pt.lbt82_kinken_sum.tesuryo20
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo20(Long tesuryo20) {
        this.tesuryo20 = tesuryo20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo21
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo21() {
        return tesuryo21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo21
     *
     * @param tesuryo21 the value for lb01_pt.lbt82_kinken_sum.tesuryo21
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo21(Long tesuryo21) {
        this.tesuryo21 = tesuryo21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo22
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo22() {
        return tesuryo22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo22
     *
     * @param tesuryo22 the value for lb01_pt.lbt82_kinken_sum.tesuryo22
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo22(Long tesuryo22) {
        this.tesuryo22 = tesuryo22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo23
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo23() {
        return tesuryo23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo23
     *
     * @param tesuryo23 the value for lb01_pt.lbt82_kinken_sum.tesuryo23
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo23(Long tesuryo23) {
        this.tesuryo23 = tesuryo23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo24
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo24() {
        return tesuryo24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo24
     *
     * @param tesuryo24 the value for lb01_pt.lbt82_kinken_sum.tesuryo24
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo24(Long tesuryo24) {
        this.tesuryo24 = tesuryo24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo25
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo25() {
        return tesuryo25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo25
     *
     * @param tesuryo25 the value for lb01_pt.lbt82_kinken_sum.tesuryo25
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo25(Long tesuryo25) {
        this.tesuryo25 = tesuryo25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo26
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo26() {
        return tesuryo26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo26
     *
     * @param tesuryo26 the value for lb01_pt.lbt82_kinken_sum.tesuryo26
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo26(Long tesuryo26) {
        this.tesuryo26 = tesuryo26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo27
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo27() {
        return tesuryo27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo27
     *
     * @param tesuryo27 the value for lb01_pt.lbt82_kinken_sum.tesuryo27
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo27(Long tesuryo27) {
        this.tesuryo27 = tesuryo27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo28
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo28() {
        return tesuryo28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo28
     *
     * @param tesuryo28 the value for lb01_pt.lbt82_kinken_sum.tesuryo28
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo28(Long tesuryo28) {
        this.tesuryo28 = tesuryo28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo29
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo29() {
        return tesuryo29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo29
     *
     * @param tesuryo29 the value for lb01_pt.lbt82_kinken_sum.tesuryo29
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo29(Long tesuryo29) {
        this.tesuryo29 = tesuryo29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo30
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryo30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Long getTesuryo30() {
        return tesuryo30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryo30
     *
     * @param tesuryo30 the value for lb01_pt.lbt82_kinken_sum.tesuryo30
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryo30(Long tesuryo30) {
        this.tesuryo30 = tesuryo30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryoshorihoho
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryoshorihoho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getTesuryoshorihoho() {
        return tesuryoshorihoho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryoshorihoho
     *
     * @param tesuryoshorihoho the value for lb01_pt.lbt82_kinken_sum.tesuryoshorihoho
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryoshorihoho(String tesuryoshorihoho) {
        this.tesuryoshorihoho = tesuryoshorihoho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.tesuryocalc_ymd
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.tesuryocalc_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Integer getTesuryocalcYmd() {
        return tesuryocalcYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.tesuryocalc_ymd
     *
     * @param tesuryocalcYmd the value for lb01_pt.lbt82_kinken_sum.tesuryocalc_ymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setTesuryocalcYmd(Integer tesuryocalcYmd) {
        this.tesuryocalcYmd = tesuryocalcYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.deldte
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Date getDeldte() {
        return deldte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.deldte
     *
     * @param deldte the value for lb01_pt.lbt82_kinken_sum.deldte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setDeldte(Date deldte) {
        this.deldte = deldte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.instdte
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Date getInstdte() {
        return instdte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.instdte
     *
     * @param instdte the value for lb01_pt.lbt82_kinken_sum.instdte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setInstdte(Date instdte) {
        this.instdte = instdte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.instusrid
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getInstusrid() {
        return instusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.instusrid
     *
     * @param instusrid the value for lb01_pt.lbt82_kinken_sum.instusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setInstusrid(String instusrid) {
        this.instusrid = instusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.instprgid
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getInstprgid() {
        return instprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.instprgid
     *
     * @param instprgid the value for lb01_pt.lbt82_kinken_sum.instprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setInstprgid(String instprgid) {
        this.instprgid = instprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.insipaddr
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getInsipaddr() {
        return insipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.insipaddr
     *
     * @param insipaddr the value for lb01_pt.lbt82_kinken_sum.insipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setInsipaddr(String insipaddr) {
        this.insipaddr = insipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.upddte
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Date getUpddte() {
        return upddte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.upddte
     *
     * @param upddte the value for lb01_pt.lbt82_kinken_sum.upddte
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUpddte(Date upddte) {
        this.upddte = upddte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.updusrid
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUpdusrid() {
        return updusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.updusrid
     *
     * @param updusrid the value for lb01_pt.lbt82_kinken_sum.updusrid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUpdusrid(String updusrid) {
        this.updusrid = updusrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.updprgid
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUpdprgid() {
        return updprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.updprgid
     *
     * @param updprgid the value for lb01_pt.lbt82_kinken_sum.updprgid
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUpdprgid(String updprgid) {
        this.updprgid = updprgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbt82_kinken_sum.updipaddr
     *
     * @return the value of lb01_pt.lbt82_kinken_sum.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getUpdipaddr() {
        return updipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbt82_kinken_sum.updipaddr
     *
     * @param updipaddr the value for lb01_pt.lbt82_kinken_sum.updipaddr
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setUpdipaddr(String updipaddr) {
        this.updipaddr = updipaddr;
    }
}