package com.feast.kanjo.entity;

public class Lbw97Gaisyopos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.ymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Integer ymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String sysgrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String kgygrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String tencd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.gaisyo_tanto_no
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String gaisyoTantoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.uriaged_bik
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private Long uriagedBik;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String hinban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.shohincd13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String shohincd13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.ntv_deal_kind1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String ntvDealKind1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.kingaku_nyukinkubun
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String kingakuNyukinkubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.card_denpyo_flg_gaisyo
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String cardDenpyoFlgGaisyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String saijicd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.hasseikeijokbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String hasseikeijokbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lbw97_gaisyopos.gaisho_kbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    private String gaishoKbn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.ymd
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.ymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Integer getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.ymd
     *
     * @param ymd the value for lb01_pt.lbw97_gaisyopos.ymd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setYmd(Integer ymd) {
        this.ymd = ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.sysgrpcd
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getSysgrpcd() {
        return sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.sysgrpcd
     *
     * @param sysgrpcd the value for lb01_pt.lbw97_gaisyopos.sysgrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setSysgrpcd(String sysgrpcd) {
        this.sysgrpcd = sysgrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.kgygrpcd
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getKgygrpcd() {
        return kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.kgygrpcd
     *
     * @param kgygrpcd the value for lb01_pt.lbw97_gaisyopos.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setKgygrpcd(String kgygrpcd) {
        this.kgygrpcd = kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.tencd
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getTencd() {
        return tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.tencd
     *
     * @param tencd the value for lb01_pt.lbw97_gaisyopos.tencd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setTencd(String tencd) {
        this.tencd = tencd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.gaisyo_tanto_no
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.gaisyo_tanto_no
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getGaisyoTantoNo() {
        return gaisyoTantoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.gaisyo_tanto_no
     *
     * @param gaisyoTantoNo the value for lb01_pt.lbw97_gaisyopos.gaisyo_tanto_no
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setGaisyoTantoNo(String gaisyoTantoNo) {
        this.gaisyoTantoNo = gaisyoTantoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.uriaged_bik
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.uriaged_bik
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Long getUriagedBik() {
        return uriagedBik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.uriaged_bik
     *
     * @param uriagedBik the value for lb01_pt.lbw97_gaisyopos.uriaged_bik
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setUriagedBik(Long uriagedBik) {
        this.uriagedBik = uriagedBik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.hinban
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getHinban() {
        return hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.hinban
     *
     * @param hinban the value for lb01_pt.lbw97_gaisyopos.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setHinban(String hinban) {
        this.hinban = hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.shohincd13
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.shohincd13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getShohincd13() {
        return shohincd13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.shohincd13
     *
     * @param shohincd13 the value for lb01_pt.lbw97_gaisyopos.shohincd13
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setShohincd13(String shohincd13) {
        this.shohincd13 = shohincd13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.ntv_deal_kind1
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.ntv_deal_kind1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getNtvDealKind1() {
        return ntvDealKind1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.ntv_deal_kind1
     *
     * @param ntvDealKind1 the value for lb01_pt.lbw97_gaisyopos.ntv_deal_kind1
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setNtvDealKind1(String ntvDealKind1) {
        this.ntvDealKind1 = ntvDealKind1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.kingaku_nyukinkubun
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.kingaku_nyukinkubun
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getKingakuNyukinkubun() {
        return kingakuNyukinkubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.kingaku_nyukinkubun
     *
     * @param kingakuNyukinkubun the value for lb01_pt.lbw97_gaisyopos.kingaku_nyukinkubun
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setKingakuNyukinkubun(String kingakuNyukinkubun) {
        this.kingakuNyukinkubun = kingakuNyukinkubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.card_denpyo_flg_gaisyo
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.card_denpyo_flg_gaisyo
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getCardDenpyoFlgGaisyo() {
        return cardDenpyoFlgGaisyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.card_denpyo_flg_gaisyo
     *
     * @param cardDenpyoFlgGaisyo the value for lb01_pt.lbw97_gaisyopos.card_denpyo_flg_gaisyo
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setCardDenpyoFlgGaisyo(String cardDenpyoFlgGaisyo) {
        this.cardDenpyoFlgGaisyo = cardDenpyoFlgGaisyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.saijicd
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getSaijicd() {
        return saijicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.saijicd
     *
     * @param saijicd the value for lb01_pt.lbw97_gaisyopos.saijicd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setSaijicd(String saijicd) {
        this.saijicd = saijicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.hasseikeijokbn
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.hasseikeijokbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getHasseikeijokbn() {
        return hasseikeijokbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.hasseikeijokbn
     *
     * @param hasseikeijokbn the value for lb01_pt.lbw97_gaisyopos.hasseikeijokbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setHasseikeijokbn(String hasseikeijokbn) {
        this.hasseikeijokbn = hasseikeijokbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lbw97_gaisyopos.gaisho_kbn
     *
     * @return the value of lb01_pt.lbw97_gaisyopos.gaisho_kbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getGaishoKbn() {
        return gaishoKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lbw97_gaisyopos.gaisho_kbn
     *
     * @param gaishoKbn the value for lb01_pt.lbw97_gaisyopos.gaisho_kbn
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setGaishoKbn(String gaishoKbn) {
        this.gaishoKbn = gaishoKbn;
    }
}