package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Lbwa3ZairyozaidPkey;
import com.feast.kanjo.entity.Lbwa3ZairyozaidPkeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Lbwa3ZairyozaidPkeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Lbwa3ZairyozaidPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Lbwa3ZairyozaidPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Lbwa3ZairyozaidPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Lbwa3ZairyozaidPkey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Lbwa3ZairyozaidPkey> selectByExample(Lbwa3ZairyozaidPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Lbwa3ZairyozaidPkey record, @Param("example") Lbwa3ZairyozaidPkeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lbwa3_zairyozaid_pkey
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Lbwa3ZairyozaidPkey record, @Param("example") Lbwa3ZairyozaidPkeyExample example);
}