package com.feast.kanjo.entity;

import java.util.Date;

public class Lma08HinbanPkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lma08_hinban_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String kgygrpcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lma08_hinban_pkey.misecd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String misecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lma08_hinban_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private String hinban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb01_pt.lma08_hinban_pkey.startymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    private Date startymd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lma08_hinban_pkey.kgygrpcd
     *
     * @return the value of lb01_pt.lma08_hinban_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getKgygrpcd() {
        return kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lma08_hinban_pkey.kgygrpcd
     *
     * @param kgygrpcd the value for lb01_pt.lma08_hinban_pkey.kgygrpcd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setKgygrpcd(String kgygrpcd) {
        this.kgygrpcd = kgygrpcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lma08_hinban_pkey.misecd
     *
     * @return the value of lb01_pt.lma08_hinban_pkey.misecd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getMisecd() {
        return misecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lma08_hinban_pkey.misecd
     *
     * @param misecd the value for lb01_pt.lma08_hinban_pkey.misecd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setMisecd(String misecd) {
        this.misecd = misecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lma08_hinban_pkey.hinban
     *
     * @return the value of lb01_pt.lma08_hinban_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public String getHinban() {
        return hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lma08_hinban_pkey.hinban
     *
     * @param hinban the value for lb01_pt.lma08_hinban_pkey.hinban
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setHinban(String hinban) {
        this.hinban = hinban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb01_pt.lma08_hinban_pkey.startymd
     *
     * @return the value of lb01_pt.lma08_hinban_pkey.startymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public Date getStartymd() {
        return startymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb01_pt.lma08_hinban_pkey.startymd
     *
     * @param startymd the value for lb01_pt.lma08_hinban_pkey.startymd
     *
     * @mbggenerated Mon Jan 22 17:43:51 CST 2018
     */
    public void setStartymd(Date startymd) {
        this.startymd = startymd;
    }
}