package com.feast.kanjo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Lmm91CdnmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Lmm91CdnmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKgygrpcdIsNull() {
            addCriterion("kgygrpcd is null");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdIsNotNull() {
            addCriterion("kgygrpcd is not null");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdEqualTo(String value) {
            addCriterion("kgygrpcd =", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdNotEqualTo(String value) {
            addCriterion("kgygrpcd <>", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdGreaterThan(String value) {
            addCriterion("kgygrpcd >", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdGreaterThanOrEqualTo(String value) {
            addCriterion("kgygrpcd >=", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdLessThan(String value) {
            addCriterion("kgygrpcd <", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdLessThanOrEqualTo(String value) {
            addCriterion("kgygrpcd <=", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdLike(String value) {
            addCriterion("kgygrpcd like", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdNotLike(String value) {
            addCriterion("kgygrpcd not like", value, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdIn(List<String> values) {
            addCriterion("kgygrpcd in", values, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdNotIn(List<String> values) {
            addCriterion("kgygrpcd not in", values, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdBetween(String value1, String value2) {
            addCriterion("kgygrpcd between", value1, value2, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andKgygrpcdNotBetween(String value1, String value2) {
            addCriterion("kgygrpcd not between", value1, value2, "kgygrpcd");
            return (Criteria) this;
        }

        public Criteria andSysidIsNull() {
            addCriterion("sysid is null");
            return (Criteria) this;
        }

        public Criteria andSysidIsNotNull() {
            addCriterion("sysid is not null");
            return (Criteria) this;
        }

        public Criteria andSysidEqualTo(String value) {
            addCriterion("sysid =", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotEqualTo(String value) {
            addCriterion("sysid <>", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThan(String value) {
            addCriterion("sysid >", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThanOrEqualTo(String value) {
            addCriterion("sysid >=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThan(String value) {
            addCriterion("sysid <", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThanOrEqualTo(String value) {
            addCriterion("sysid <=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLike(String value) {
            addCriterion("sysid like", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotLike(String value) {
            addCriterion("sysid not like", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidIn(List<String> values) {
            addCriterion("sysid in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotIn(List<String> values) {
            addCriterion("sysid not in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidBetween(String value1, String value2) {
            addCriterion("sysid between", value1, value2, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotBetween(String value1, String value2) {
            addCriterion("sysid not between", value1, value2, "sysid");
            return (Criteria) this;
        }

        public Criteria andCdclassIsNull() {
            addCriterion("cdclass is null");
            return (Criteria) this;
        }

        public Criteria andCdclassIsNotNull() {
            addCriterion("cdclass is not null");
            return (Criteria) this;
        }

        public Criteria andCdclassEqualTo(String value) {
            addCriterion("cdclass =", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassNotEqualTo(String value) {
            addCriterion("cdclass <>", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassGreaterThan(String value) {
            addCriterion("cdclass >", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassGreaterThanOrEqualTo(String value) {
            addCriterion("cdclass >=", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassLessThan(String value) {
            addCriterion("cdclass <", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassLessThanOrEqualTo(String value) {
            addCriterion("cdclass <=", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassLike(String value) {
            addCriterion("cdclass like", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassNotLike(String value) {
            addCriterion("cdclass not like", value, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassIn(List<String> values) {
            addCriterion("cdclass in", values, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassNotIn(List<String> values) {
            addCriterion("cdclass not in", values, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassBetween(String value1, String value2) {
            addCriterion("cdclass between", value1, value2, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdclassNotBetween(String value1, String value2) {
            addCriterion("cdclass not between", value1, value2, "cdclass");
            return (Criteria) this;
        }

        public Criteria andCdIsNull() {
            addCriterion("cd is null");
            return (Criteria) this;
        }

        public Criteria andCdIsNotNull() {
            addCriterion("cd is not null");
            return (Criteria) this;
        }

        public Criteria andCdEqualTo(String value) {
            addCriterion("cd =", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotEqualTo(String value) {
            addCriterion("cd <>", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThan(String value) {
            addCriterion("cd >", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThanOrEqualTo(String value) {
            addCriterion("cd >=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThan(String value) {
            addCriterion("cd <", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThanOrEqualTo(String value) {
            addCriterion("cd <=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLike(String value) {
            addCriterion("cd like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotLike(String value) {
            addCriterion("cd not like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdIn(List<String> values) {
            addCriterion("cd in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotIn(List<String> values) {
            addCriterion("cd not in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdBetween(String value1, String value2) {
            addCriterion("cd between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotBetween(String value1, String value2) {
            addCriterion("cd not between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCd1IsNull() {
            addCriterion("cd1 is null");
            return (Criteria) this;
        }

        public Criteria andCd1IsNotNull() {
            addCriterion("cd1 is not null");
            return (Criteria) this;
        }

        public Criteria andCd1EqualTo(String value) {
            addCriterion("cd1 =", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1NotEqualTo(String value) {
            addCriterion("cd1 <>", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1GreaterThan(String value) {
            addCriterion("cd1 >", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1GreaterThanOrEqualTo(String value) {
            addCriterion("cd1 >=", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1LessThan(String value) {
            addCriterion("cd1 <", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1LessThanOrEqualTo(String value) {
            addCriterion("cd1 <=", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1Like(String value) {
            addCriterion("cd1 like", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1NotLike(String value) {
            addCriterion("cd1 not like", value, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1In(List<String> values) {
            addCriterion("cd1 in", values, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1NotIn(List<String> values) {
            addCriterion("cd1 not in", values, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1Between(String value1, String value2) {
            addCriterion("cd1 between", value1, value2, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd1NotBetween(String value1, String value2) {
            addCriterion("cd1 not between", value1, value2, "cd1");
            return (Criteria) this;
        }

        public Criteria andCd2IsNull() {
            addCriterion("cd2 is null");
            return (Criteria) this;
        }

        public Criteria andCd2IsNotNull() {
            addCriterion("cd2 is not null");
            return (Criteria) this;
        }

        public Criteria andCd2EqualTo(String value) {
            addCriterion("cd2 =", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2NotEqualTo(String value) {
            addCriterion("cd2 <>", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2GreaterThan(String value) {
            addCriterion("cd2 >", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2GreaterThanOrEqualTo(String value) {
            addCriterion("cd2 >=", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2LessThan(String value) {
            addCriterion("cd2 <", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2LessThanOrEqualTo(String value) {
            addCriterion("cd2 <=", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2Like(String value) {
            addCriterion("cd2 like", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2NotLike(String value) {
            addCriterion("cd2 not like", value, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2In(List<String> values) {
            addCriterion("cd2 in", values, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2NotIn(List<String> values) {
            addCriterion("cd2 not in", values, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2Between(String value1, String value2) {
            addCriterion("cd2 between", value1, value2, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd2NotBetween(String value1, String value2) {
            addCriterion("cd2 not between", value1, value2, "cd2");
            return (Criteria) this;
        }

        public Criteria andCd3IsNull() {
            addCriterion("cd3 is null");
            return (Criteria) this;
        }

        public Criteria andCd3IsNotNull() {
            addCriterion("cd3 is not null");
            return (Criteria) this;
        }

        public Criteria andCd3EqualTo(String value) {
            addCriterion("cd3 =", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3NotEqualTo(String value) {
            addCriterion("cd3 <>", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3GreaterThan(String value) {
            addCriterion("cd3 >", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3GreaterThanOrEqualTo(String value) {
            addCriterion("cd3 >=", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3LessThan(String value) {
            addCriterion("cd3 <", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3LessThanOrEqualTo(String value) {
            addCriterion("cd3 <=", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3Like(String value) {
            addCriterion("cd3 like", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3NotLike(String value) {
            addCriterion("cd3 not like", value, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3In(List<String> values) {
            addCriterion("cd3 in", values, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3NotIn(List<String> values) {
            addCriterion("cd3 not in", values, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3Between(String value1, String value2) {
            addCriterion("cd3 between", value1, value2, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd3NotBetween(String value1, String value2) {
            addCriterion("cd3 not between", value1, value2, "cd3");
            return (Criteria) this;
        }

        public Criteria andCd4IsNull() {
            addCriterion("cd4 is null");
            return (Criteria) this;
        }

        public Criteria andCd4IsNotNull() {
            addCriterion("cd4 is not null");
            return (Criteria) this;
        }

        public Criteria andCd4EqualTo(String value) {
            addCriterion("cd4 =", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4NotEqualTo(String value) {
            addCriterion("cd4 <>", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4GreaterThan(String value) {
            addCriterion("cd4 >", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4GreaterThanOrEqualTo(String value) {
            addCriterion("cd4 >=", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4LessThan(String value) {
            addCriterion("cd4 <", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4LessThanOrEqualTo(String value) {
            addCriterion("cd4 <=", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4Like(String value) {
            addCriterion("cd4 like", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4NotLike(String value) {
            addCriterion("cd4 not like", value, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4In(List<String> values) {
            addCriterion("cd4 in", values, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4NotIn(List<String> values) {
            addCriterion("cd4 not in", values, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4Between(String value1, String value2) {
            addCriterion("cd4 between", value1, value2, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd4NotBetween(String value1, String value2) {
            addCriterion("cd4 not between", value1, value2, "cd4");
            return (Criteria) this;
        }

        public Criteria andCd5IsNull() {
            addCriterion("cd5 is null");
            return (Criteria) this;
        }

        public Criteria andCd5IsNotNull() {
            addCriterion("cd5 is not null");
            return (Criteria) this;
        }

        public Criteria andCd5EqualTo(String value) {
            addCriterion("cd5 =", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5NotEqualTo(String value) {
            addCriterion("cd5 <>", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5GreaterThan(String value) {
            addCriterion("cd5 >", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5GreaterThanOrEqualTo(String value) {
            addCriterion("cd5 >=", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5LessThan(String value) {
            addCriterion("cd5 <", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5LessThanOrEqualTo(String value) {
            addCriterion("cd5 <=", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5Like(String value) {
            addCriterion("cd5 like", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5NotLike(String value) {
            addCriterion("cd5 not like", value, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5In(List<String> values) {
            addCriterion("cd5 in", values, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5NotIn(List<String> values) {
            addCriterion("cd5 not in", values, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5Between(String value1, String value2) {
            addCriterion("cd5 between", value1, value2, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd5NotBetween(String value1, String value2) {
            addCriterion("cd5 not between", value1, value2, "cd5");
            return (Criteria) this;
        }

        public Criteria andCd6IsNull() {
            addCriterion("cd6 is null");
            return (Criteria) this;
        }

        public Criteria andCd6IsNotNull() {
            addCriterion("cd6 is not null");
            return (Criteria) this;
        }

        public Criteria andCd6EqualTo(String value) {
            addCriterion("cd6 =", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6NotEqualTo(String value) {
            addCriterion("cd6 <>", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6GreaterThan(String value) {
            addCriterion("cd6 >", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6GreaterThanOrEqualTo(String value) {
            addCriterion("cd6 >=", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6LessThan(String value) {
            addCriterion("cd6 <", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6LessThanOrEqualTo(String value) {
            addCriterion("cd6 <=", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6Like(String value) {
            addCriterion("cd6 like", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6NotLike(String value) {
            addCriterion("cd6 not like", value, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6In(List<String> values) {
            addCriterion("cd6 in", values, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6NotIn(List<String> values) {
            addCriterion("cd6 not in", values, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6Between(String value1, String value2) {
            addCriterion("cd6 between", value1, value2, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd6NotBetween(String value1, String value2) {
            addCriterion("cd6 not between", value1, value2, "cd6");
            return (Criteria) this;
        }

        public Criteria andCd7IsNull() {
            addCriterion("cd7 is null");
            return (Criteria) this;
        }

        public Criteria andCd7IsNotNull() {
            addCriterion("cd7 is not null");
            return (Criteria) this;
        }

        public Criteria andCd7EqualTo(String value) {
            addCriterion("cd7 =", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7NotEqualTo(String value) {
            addCriterion("cd7 <>", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7GreaterThan(String value) {
            addCriterion("cd7 >", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7GreaterThanOrEqualTo(String value) {
            addCriterion("cd7 >=", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7LessThan(String value) {
            addCriterion("cd7 <", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7LessThanOrEqualTo(String value) {
            addCriterion("cd7 <=", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7Like(String value) {
            addCriterion("cd7 like", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7NotLike(String value) {
            addCriterion("cd7 not like", value, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7In(List<String> values) {
            addCriterion("cd7 in", values, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7NotIn(List<String> values) {
            addCriterion("cd7 not in", values, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7Between(String value1, String value2) {
            addCriterion("cd7 between", value1, value2, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd7NotBetween(String value1, String value2) {
            addCriterion("cd7 not between", value1, value2, "cd7");
            return (Criteria) this;
        }

        public Criteria andCd8IsNull() {
            addCriterion("cd8 is null");
            return (Criteria) this;
        }

        public Criteria andCd8IsNotNull() {
            addCriterion("cd8 is not null");
            return (Criteria) this;
        }

        public Criteria andCd8EqualTo(String value) {
            addCriterion("cd8 =", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8NotEqualTo(String value) {
            addCriterion("cd8 <>", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8GreaterThan(String value) {
            addCriterion("cd8 >", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8GreaterThanOrEqualTo(String value) {
            addCriterion("cd8 >=", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8LessThan(String value) {
            addCriterion("cd8 <", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8LessThanOrEqualTo(String value) {
            addCriterion("cd8 <=", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8Like(String value) {
            addCriterion("cd8 like", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8NotLike(String value) {
            addCriterion("cd8 not like", value, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8In(List<String> values) {
            addCriterion("cd8 in", values, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8NotIn(List<String> values) {
            addCriterion("cd8 not in", values, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8Between(String value1, String value2) {
            addCriterion("cd8 between", value1, value2, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd8NotBetween(String value1, String value2) {
            addCriterion("cd8 not between", value1, value2, "cd8");
            return (Criteria) this;
        }

        public Criteria andCd9IsNull() {
            addCriterion("cd9 is null");
            return (Criteria) this;
        }

        public Criteria andCd9IsNotNull() {
            addCriterion("cd9 is not null");
            return (Criteria) this;
        }

        public Criteria andCd9EqualTo(String value) {
            addCriterion("cd9 =", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9NotEqualTo(String value) {
            addCriterion("cd9 <>", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9GreaterThan(String value) {
            addCriterion("cd9 >", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9GreaterThanOrEqualTo(String value) {
            addCriterion("cd9 >=", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9LessThan(String value) {
            addCriterion("cd9 <", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9LessThanOrEqualTo(String value) {
            addCriterion("cd9 <=", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9Like(String value) {
            addCriterion("cd9 like", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9NotLike(String value) {
            addCriterion("cd9 not like", value, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9In(List<String> values) {
            addCriterion("cd9 in", values, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9NotIn(List<String> values) {
            addCriterion("cd9 not in", values, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9Between(String value1, String value2) {
            addCriterion("cd9 between", value1, value2, "cd9");
            return (Criteria) this;
        }

        public Criteria andCd9NotBetween(String value1, String value2) {
            addCriterion("cd9 not between", value1, value2, "cd9");
            return (Criteria) this;
        }

        public Criteria andStartymdIsNull() {
            addCriterion("startymd is null");
            return (Criteria) this;
        }

        public Criteria andStartymdIsNotNull() {
            addCriterion("startymd is not null");
            return (Criteria) this;
        }

        public Criteria andStartymdEqualTo(Date value) {
            addCriterion("startymd =", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdNotEqualTo(Date value) {
            addCriterion("startymd <>", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdGreaterThan(Date value) {
            addCriterion("startymd >", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdGreaterThanOrEqualTo(Date value) {
            addCriterion("startymd >=", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdLessThan(Date value) {
            addCriterion("startymd <", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdLessThanOrEqualTo(Date value) {
            addCriterion("startymd <=", value, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdIn(List<Date> values) {
            addCriterion("startymd in", values, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdNotIn(List<Date> values) {
            addCriterion("startymd not in", values, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdBetween(Date value1, Date value2) {
            addCriterion("startymd between", value1, value2, "startymd");
            return (Criteria) this;
        }

        public Criteria andStartymdNotBetween(Date value1, Date value2) {
            addCriterion("startymd not between", value1, value2, "startymd");
            return (Criteria) this;
        }

        public Criteria andEndymdIsNull() {
            addCriterion("endymd is null");
            return (Criteria) this;
        }

        public Criteria andEndymdIsNotNull() {
            addCriterion("endymd is not null");
            return (Criteria) this;
        }

        public Criteria andEndymdEqualTo(Date value) {
            addCriterion("endymd =", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdNotEqualTo(Date value) {
            addCriterion("endymd <>", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdGreaterThan(Date value) {
            addCriterion("endymd >", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdGreaterThanOrEqualTo(Date value) {
            addCriterion("endymd >=", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdLessThan(Date value) {
            addCriterion("endymd <", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdLessThanOrEqualTo(Date value) {
            addCriterion("endymd <=", value, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdIn(List<Date> values) {
            addCriterion("endymd in", values, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdNotIn(List<Date> values) {
            addCriterion("endymd not in", values, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdBetween(Date value1, Date value2) {
            addCriterion("endymd between", value1, value2, "endymd");
            return (Criteria) this;
        }

        public Criteria andEndymdNotBetween(Date value1, Date value2) {
            addCriterion("endymd not between", value1, value2, "endymd");
            return (Criteria) this;
        }

        public Criteria andCdnmkjIsNull() {
            addCriterion("cdnmkj is null");
            return (Criteria) this;
        }

        public Criteria andCdnmkjIsNotNull() {
            addCriterion("cdnmkj is not null");
            return (Criteria) this;
        }

        public Criteria andCdnmkjEqualTo(String value) {
            addCriterion("cdnmkj =", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjNotEqualTo(String value) {
            addCriterion("cdnmkj <>", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjGreaterThan(String value) {
            addCriterion("cdnmkj >", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjGreaterThanOrEqualTo(String value) {
            addCriterion("cdnmkj >=", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjLessThan(String value) {
            addCriterion("cdnmkj <", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjLessThanOrEqualTo(String value) {
            addCriterion("cdnmkj <=", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjLike(String value) {
            addCriterion("cdnmkj like", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjNotLike(String value) {
            addCriterion("cdnmkj not like", value, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjIn(List<String> values) {
            addCriterion("cdnmkj in", values, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjNotIn(List<String> values) {
            addCriterion("cdnmkj not in", values, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjBetween(String value1, String value2) {
            addCriterion("cdnmkj between", value1, value2, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmkjNotBetween(String value1, String value2) {
            addCriterion("cdnmkj not between", value1, value2, "cdnmkj");
            return (Criteria) this;
        }

        public Criteria andCdnmknIsNull() {
            addCriterion("cdnmkn is null");
            return (Criteria) this;
        }

        public Criteria andCdnmknIsNotNull() {
            addCriterion("cdnmkn is not null");
            return (Criteria) this;
        }

        public Criteria andCdnmknEqualTo(String value) {
            addCriterion("cdnmkn =", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknNotEqualTo(String value) {
            addCriterion("cdnmkn <>", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknGreaterThan(String value) {
            addCriterion("cdnmkn >", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknGreaterThanOrEqualTo(String value) {
            addCriterion("cdnmkn >=", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknLessThan(String value) {
            addCriterion("cdnmkn <", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknLessThanOrEqualTo(String value) {
            addCriterion("cdnmkn <=", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknLike(String value) {
            addCriterion("cdnmkn like", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknNotLike(String value) {
            addCriterion("cdnmkn not like", value, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknIn(List<String> values) {
            addCriterion("cdnmkn in", values, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknNotIn(List<String> values) {
            addCriterion("cdnmkn not in", values, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknBetween(String value1, String value2) {
            addCriterion("cdnmkn between", value1, value2, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andCdnmknNotBetween(String value1, String value2) {
            addCriterion("cdnmkn not between", value1, value2, "cdnmkn");
            return (Criteria) this;
        }

        public Criteria andYobichr1IsNull() {
            addCriterion("yobichr1 is null");
            return (Criteria) this;
        }

        public Criteria andYobichr1IsNotNull() {
            addCriterion("yobichr1 is not null");
            return (Criteria) this;
        }

        public Criteria andYobichr1EqualTo(String value) {
            addCriterion("yobichr1 =", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1NotEqualTo(String value) {
            addCriterion("yobichr1 <>", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1GreaterThan(String value) {
            addCriterion("yobichr1 >", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1GreaterThanOrEqualTo(String value) {
            addCriterion("yobichr1 >=", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1LessThan(String value) {
            addCriterion("yobichr1 <", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1LessThanOrEqualTo(String value) {
            addCriterion("yobichr1 <=", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1Like(String value) {
            addCriterion("yobichr1 like", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1NotLike(String value) {
            addCriterion("yobichr1 not like", value, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1In(List<String> values) {
            addCriterion("yobichr1 in", values, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1NotIn(List<String> values) {
            addCriterion("yobichr1 not in", values, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1Between(String value1, String value2) {
            addCriterion("yobichr1 between", value1, value2, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr1NotBetween(String value1, String value2) {
            addCriterion("yobichr1 not between", value1, value2, "yobichr1");
            return (Criteria) this;
        }

        public Criteria andYobichr2IsNull() {
            addCriterion("yobichr2 is null");
            return (Criteria) this;
        }

        public Criteria andYobichr2IsNotNull() {
            addCriterion("yobichr2 is not null");
            return (Criteria) this;
        }

        public Criteria andYobichr2EqualTo(String value) {
            addCriterion("yobichr2 =", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2NotEqualTo(String value) {
            addCriterion("yobichr2 <>", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2GreaterThan(String value) {
            addCriterion("yobichr2 >", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2GreaterThanOrEqualTo(String value) {
            addCriterion("yobichr2 >=", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2LessThan(String value) {
            addCriterion("yobichr2 <", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2LessThanOrEqualTo(String value) {
            addCriterion("yobichr2 <=", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2Like(String value) {
            addCriterion("yobichr2 like", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2NotLike(String value) {
            addCriterion("yobichr2 not like", value, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2In(List<String> values) {
            addCriterion("yobichr2 in", values, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2NotIn(List<String> values) {
            addCriterion("yobichr2 not in", values, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2Between(String value1, String value2) {
            addCriterion("yobichr2 between", value1, value2, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr2NotBetween(String value1, String value2) {
            addCriterion("yobichr2 not between", value1, value2, "yobichr2");
            return (Criteria) this;
        }

        public Criteria andYobichr3IsNull() {
            addCriterion("yobichr3 is null");
            return (Criteria) this;
        }

        public Criteria andYobichr3IsNotNull() {
            addCriterion("yobichr3 is not null");
            return (Criteria) this;
        }

        public Criteria andYobichr3EqualTo(String value) {
            addCriterion("yobichr3 =", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3NotEqualTo(String value) {
            addCriterion("yobichr3 <>", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3GreaterThan(String value) {
            addCriterion("yobichr3 >", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3GreaterThanOrEqualTo(String value) {
            addCriterion("yobichr3 >=", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3LessThan(String value) {
            addCriterion("yobichr3 <", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3LessThanOrEqualTo(String value) {
            addCriterion("yobichr3 <=", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3Like(String value) {
            addCriterion("yobichr3 like", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3NotLike(String value) {
            addCriterion("yobichr3 not like", value, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3In(List<String> values) {
            addCriterion("yobichr3 in", values, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3NotIn(List<String> values) {
            addCriterion("yobichr3 not in", values, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3Between(String value1, String value2) {
            addCriterion("yobichr3 between", value1, value2, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr3NotBetween(String value1, String value2) {
            addCriterion("yobichr3 not between", value1, value2, "yobichr3");
            return (Criteria) this;
        }

        public Criteria andYobichr4IsNull() {
            addCriterion("yobichr4 is null");
            return (Criteria) this;
        }

        public Criteria andYobichr4IsNotNull() {
            addCriterion("yobichr4 is not null");
            return (Criteria) this;
        }

        public Criteria andYobichr4EqualTo(String value) {
            addCriterion("yobichr4 =", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4NotEqualTo(String value) {
            addCriterion("yobichr4 <>", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4GreaterThan(String value) {
            addCriterion("yobichr4 >", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4GreaterThanOrEqualTo(String value) {
            addCriterion("yobichr4 >=", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4LessThan(String value) {
            addCriterion("yobichr4 <", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4LessThanOrEqualTo(String value) {
            addCriterion("yobichr4 <=", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4Like(String value) {
            addCriterion("yobichr4 like", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4NotLike(String value) {
            addCriterion("yobichr4 not like", value, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4In(List<String> values) {
            addCriterion("yobichr4 in", values, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4NotIn(List<String> values) {
            addCriterion("yobichr4 not in", values, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4Between(String value1, String value2) {
            addCriterion("yobichr4 between", value1, value2, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr4NotBetween(String value1, String value2) {
            addCriterion("yobichr4 not between", value1, value2, "yobichr4");
            return (Criteria) this;
        }

        public Criteria andYobichr5IsNull() {
            addCriterion("yobichr5 is null");
            return (Criteria) this;
        }

        public Criteria andYobichr5IsNotNull() {
            addCriterion("yobichr5 is not null");
            return (Criteria) this;
        }

        public Criteria andYobichr5EqualTo(String value) {
            addCriterion("yobichr5 =", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5NotEqualTo(String value) {
            addCriterion("yobichr5 <>", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5GreaterThan(String value) {
            addCriterion("yobichr5 >", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5GreaterThanOrEqualTo(String value) {
            addCriterion("yobichr5 >=", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5LessThan(String value) {
            addCriterion("yobichr5 <", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5LessThanOrEqualTo(String value) {
            addCriterion("yobichr5 <=", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5Like(String value) {
            addCriterion("yobichr5 like", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5NotLike(String value) {
            addCriterion("yobichr5 not like", value, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5In(List<String> values) {
            addCriterion("yobichr5 in", values, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5NotIn(List<String> values) {
            addCriterion("yobichr5 not in", values, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5Between(String value1, String value2) {
            addCriterion("yobichr5 between", value1, value2, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobichr5NotBetween(String value1, String value2) {
            addCriterion("yobichr5 not between", value1, value2, "yobichr5");
            return (Criteria) this;
        }

        public Criteria andYobinum1IsNull() {
            addCriterion("yobinum1 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum1IsNotNull() {
            addCriterion("yobinum1 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum1EqualTo(Long value) {
            addCriterion("yobinum1 =", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1NotEqualTo(Long value) {
            addCriterion("yobinum1 <>", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1GreaterThan(Long value) {
            addCriterion("yobinum1 >", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum1 >=", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1LessThan(Long value) {
            addCriterion("yobinum1 <", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1LessThanOrEqualTo(Long value) {
            addCriterion("yobinum1 <=", value, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1In(List<Long> values) {
            addCriterion("yobinum1 in", values, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1NotIn(List<Long> values) {
            addCriterion("yobinum1 not in", values, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1Between(Long value1, Long value2) {
            addCriterion("yobinum1 between", value1, value2, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum1NotBetween(Long value1, Long value2) {
            addCriterion("yobinum1 not between", value1, value2, "yobinum1");
            return (Criteria) this;
        }

        public Criteria andYobinum2IsNull() {
            addCriterion("yobinum2 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum2IsNotNull() {
            addCriterion("yobinum2 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum2EqualTo(Long value) {
            addCriterion("yobinum2 =", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2NotEqualTo(Long value) {
            addCriterion("yobinum2 <>", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2GreaterThan(Long value) {
            addCriterion("yobinum2 >", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum2 >=", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2LessThan(Long value) {
            addCriterion("yobinum2 <", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2LessThanOrEqualTo(Long value) {
            addCriterion("yobinum2 <=", value, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2In(List<Long> values) {
            addCriterion("yobinum2 in", values, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2NotIn(List<Long> values) {
            addCriterion("yobinum2 not in", values, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2Between(Long value1, Long value2) {
            addCriterion("yobinum2 between", value1, value2, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum2NotBetween(Long value1, Long value2) {
            addCriterion("yobinum2 not between", value1, value2, "yobinum2");
            return (Criteria) this;
        }

        public Criteria andYobinum3IsNull() {
            addCriterion("yobinum3 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum3IsNotNull() {
            addCriterion("yobinum3 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum3EqualTo(Long value) {
            addCriterion("yobinum3 =", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3NotEqualTo(Long value) {
            addCriterion("yobinum3 <>", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3GreaterThan(Long value) {
            addCriterion("yobinum3 >", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum3 >=", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3LessThan(Long value) {
            addCriterion("yobinum3 <", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3LessThanOrEqualTo(Long value) {
            addCriterion("yobinum3 <=", value, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3In(List<Long> values) {
            addCriterion("yobinum3 in", values, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3NotIn(List<Long> values) {
            addCriterion("yobinum3 not in", values, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3Between(Long value1, Long value2) {
            addCriterion("yobinum3 between", value1, value2, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum3NotBetween(Long value1, Long value2) {
            addCriterion("yobinum3 not between", value1, value2, "yobinum3");
            return (Criteria) this;
        }

        public Criteria andYobinum4IsNull() {
            addCriterion("yobinum4 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum4IsNotNull() {
            addCriterion("yobinum4 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum4EqualTo(Long value) {
            addCriterion("yobinum4 =", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4NotEqualTo(Long value) {
            addCriterion("yobinum4 <>", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4GreaterThan(Long value) {
            addCriterion("yobinum4 >", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum4 >=", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4LessThan(Long value) {
            addCriterion("yobinum4 <", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4LessThanOrEqualTo(Long value) {
            addCriterion("yobinum4 <=", value, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4In(List<Long> values) {
            addCriterion("yobinum4 in", values, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4NotIn(List<Long> values) {
            addCriterion("yobinum4 not in", values, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4Between(Long value1, Long value2) {
            addCriterion("yobinum4 between", value1, value2, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum4NotBetween(Long value1, Long value2) {
            addCriterion("yobinum4 not between", value1, value2, "yobinum4");
            return (Criteria) this;
        }

        public Criteria andYobinum5IsNull() {
            addCriterion("yobinum5 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum5IsNotNull() {
            addCriterion("yobinum5 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum5EqualTo(Long value) {
            addCriterion("yobinum5 =", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5NotEqualTo(Long value) {
            addCriterion("yobinum5 <>", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5GreaterThan(Long value) {
            addCriterion("yobinum5 >", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum5 >=", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5LessThan(Long value) {
            addCriterion("yobinum5 <", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5LessThanOrEqualTo(Long value) {
            addCriterion("yobinum5 <=", value, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5In(List<Long> values) {
            addCriterion("yobinum5 in", values, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5NotIn(List<Long> values) {
            addCriterion("yobinum5 not in", values, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5Between(Long value1, Long value2) {
            addCriterion("yobinum5 between", value1, value2, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum5NotBetween(Long value1, Long value2) {
            addCriterion("yobinum5 not between", value1, value2, "yobinum5");
            return (Criteria) this;
        }

        public Criteria andYobinum6IsNull() {
            addCriterion("yobinum6 is null");
            return (Criteria) this;
        }

        public Criteria andYobinum6IsNotNull() {
            addCriterion("yobinum6 is not null");
            return (Criteria) this;
        }

        public Criteria andYobinum6EqualTo(Long value) {
            addCriterion("yobinum6 =", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6NotEqualTo(Long value) {
            addCriterion("yobinum6 <>", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6GreaterThan(Long value) {
            addCriterion("yobinum6 >", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6GreaterThanOrEqualTo(Long value) {
            addCriterion("yobinum6 >=", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6LessThan(Long value) {
            addCriterion("yobinum6 <", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6LessThanOrEqualTo(Long value) {
            addCriterion("yobinum6 <=", value, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6In(List<Long> values) {
            addCriterion("yobinum6 in", values, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6NotIn(List<Long> values) {
            addCriterion("yobinum6 not in", values, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6Between(Long value1, Long value2) {
            addCriterion("yobinum6 between", value1, value2, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andYobinum6NotBetween(Long value1, Long value2) {
            addCriterion("yobinum6 not between", value1, value2, "yobinum6");
            return (Criteria) this;
        }

        public Criteria andDeldteIsNull() {
            addCriterion("deldte is null");
            return (Criteria) this;
        }

        public Criteria andDeldteIsNotNull() {
            addCriterion("deldte is not null");
            return (Criteria) this;
        }

        public Criteria andDeldteEqualTo(Date value) {
            addCriterion("deldte =", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotEqualTo(Date value) {
            addCriterion("deldte <>", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteGreaterThan(Date value) {
            addCriterion("deldte >", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteGreaterThanOrEqualTo(Date value) {
            addCriterion("deldte >=", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteLessThan(Date value) {
            addCriterion("deldte <", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteLessThanOrEqualTo(Date value) {
            addCriterion("deldte <=", value, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteIn(List<Date> values) {
            addCriterion("deldte in", values, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotIn(List<Date> values) {
            addCriterion("deldte not in", values, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteBetween(Date value1, Date value2) {
            addCriterion("deldte between", value1, value2, "deldte");
            return (Criteria) this;
        }

        public Criteria andDeldteNotBetween(Date value1, Date value2) {
            addCriterion("deldte not between", value1, value2, "deldte");
            return (Criteria) this;
        }

        public Criteria andInstdteIsNull() {
            addCriterion("instdte is null");
            return (Criteria) this;
        }

        public Criteria andInstdteIsNotNull() {
            addCriterion("instdte is not null");
            return (Criteria) this;
        }

        public Criteria andInstdteEqualTo(Date value) {
            addCriterion("instdte =", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotEqualTo(Date value) {
            addCriterion("instdte <>", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteGreaterThan(Date value) {
            addCriterion("instdte >", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteGreaterThanOrEqualTo(Date value) {
            addCriterion("instdte >=", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteLessThan(Date value) {
            addCriterion("instdte <", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteLessThanOrEqualTo(Date value) {
            addCriterion("instdte <=", value, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteIn(List<Date> values) {
            addCriterion("instdte in", values, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotIn(List<Date> values) {
            addCriterion("instdte not in", values, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteBetween(Date value1, Date value2) {
            addCriterion("instdte between", value1, value2, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstdteNotBetween(Date value1, Date value2) {
            addCriterion("instdte not between", value1, value2, "instdte");
            return (Criteria) this;
        }

        public Criteria andInstusridIsNull() {
            addCriterion("instusrid is null");
            return (Criteria) this;
        }

        public Criteria andInstusridIsNotNull() {
            addCriterion("instusrid is not null");
            return (Criteria) this;
        }

        public Criteria andInstusridEqualTo(String value) {
            addCriterion("instusrid =", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotEqualTo(String value) {
            addCriterion("instusrid <>", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridGreaterThan(String value) {
            addCriterion("instusrid >", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridGreaterThanOrEqualTo(String value) {
            addCriterion("instusrid >=", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLessThan(String value) {
            addCriterion("instusrid <", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLessThanOrEqualTo(String value) {
            addCriterion("instusrid <=", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridLike(String value) {
            addCriterion("instusrid like", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotLike(String value) {
            addCriterion("instusrid not like", value, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridIn(List<String> values) {
            addCriterion("instusrid in", values, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotIn(List<String> values) {
            addCriterion("instusrid not in", values, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridBetween(String value1, String value2) {
            addCriterion("instusrid between", value1, value2, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstusridNotBetween(String value1, String value2) {
            addCriterion("instusrid not between", value1, value2, "instusrid");
            return (Criteria) this;
        }

        public Criteria andInstprgidIsNull() {
            addCriterion("instprgid is null");
            return (Criteria) this;
        }

        public Criteria andInstprgidIsNotNull() {
            addCriterion("instprgid is not null");
            return (Criteria) this;
        }

        public Criteria andInstprgidEqualTo(String value) {
            addCriterion("instprgid =", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotEqualTo(String value) {
            addCriterion("instprgid <>", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidGreaterThan(String value) {
            addCriterion("instprgid >", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidGreaterThanOrEqualTo(String value) {
            addCriterion("instprgid >=", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLessThan(String value) {
            addCriterion("instprgid <", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLessThanOrEqualTo(String value) {
            addCriterion("instprgid <=", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidLike(String value) {
            addCriterion("instprgid like", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotLike(String value) {
            addCriterion("instprgid not like", value, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidIn(List<String> values) {
            addCriterion("instprgid in", values, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotIn(List<String> values) {
            addCriterion("instprgid not in", values, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidBetween(String value1, String value2) {
            addCriterion("instprgid between", value1, value2, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInstprgidNotBetween(String value1, String value2) {
            addCriterion("instprgid not between", value1, value2, "instprgid");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIsNull() {
            addCriterion("insipaddr is null");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIsNotNull() {
            addCriterion("insipaddr is not null");
            return (Criteria) this;
        }

        public Criteria andInsipaddrEqualTo(String value) {
            addCriterion("insipaddr =", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotEqualTo(String value) {
            addCriterion("insipaddr <>", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrGreaterThan(String value) {
            addCriterion("insipaddr >", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrGreaterThanOrEqualTo(String value) {
            addCriterion("insipaddr >=", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLessThan(String value) {
            addCriterion("insipaddr <", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLessThanOrEqualTo(String value) {
            addCriterion("insipaddr <=", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrLike(String value) {
            addCriterion("insipaddr like", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotLike(String value) {
            addCriterion("insipaddr not like", value, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrIn(List<String> values) {
            addCriterion("insipaddr in", values, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotIn(List<String> values) {
            addCriterion("insipaddr not in", values, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrBetween(String value1, String value2) {
            addCriterion("insipaddr between", value1, value2, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andInsipaddrNotBetween(String value1, String value2) {
            addCriterion("insipaddr not between", value1, value2, "insipaddr");
            return (Criteria) this;
        }

        public Criteria andUpddteIsNull() {
            addCriterion("upddte is null");
            return (Criteria) this;
        }

        public Criteria andUpddteIsNotNull() {
            addCriterion("upddte is not null");
            return (Criteria) this;
        }

        public Criteria andUpddteEqualTo(Date value) {
            addCriterion("upddte =", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotEqualTo(Date value) {
            addCriterion("upddte <>", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteGreaterThan(Date value) {
            addCriterion("upddte >", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteGreaterThanOrEqualTo(Date value) {
            addCriterion("upddte >=", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteLessThan(Date value) {
            addCriterion("upddte <", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteLessThanOrEqualTo(Date value) {
            addCriterion("upddte <=", value, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteIn(List<Date> values) {
            addCriterion("upddte in", values, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotIn(List<Date> values) {
            addCriterion("upddte not in", values, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteBetween(Date value1, Date value2) {
            addCriterion("upddte between", value1, value2, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpddteNotBetween(Date value1, Date value2) {
            addCriterion("upddte not between", value1, value2, "upddte");
            return (Criteria) this;
        }

        public Criteria andUpdusridIsNull() {
            addCriterion("updusrid is null");
            return (Criteria) this;
        }

        public Criteria andUpdusridIsNotNull() {
            addCriterion("updusrid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdusridEqualTo(String value) {
            addCriterion("updusrid =", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotEqualTo(String value) {
            addCriterion("updusrid <>", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridGreaterThan(String value) {
            addCriterion("updusrid >", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridGreaterThanOrEqualTo(String value) {
            addCriterion("updusrid >=", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLessThan(String value) {
            addCriterion("updusrid <", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLessThanOrEqualTo(String value) {
            addCriterion("updusrid <=", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridLike(String value) {
            addCriterion("updusrid like", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotLike(String value) {
            addCriterion("updusrid not like", value, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridIn(List<String> values) {
            addCriterion("updusrid in", values, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotIn(List<String> values) {
            addCriterion("updusrid not in", values, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridBetween(String value1, String value2) {
            addCriterion("updusrid between", value1, value2, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdusridNotBetween(String value1, String value2) {
            addCriterion("updusrid not between", value1, value2, "updusrid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIsNull() {
            addCriterion("updprgid is null");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIsNotNull() {
            addCriterion("updprgid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdprgidEqualTo(String value) {
            addCriterion("updprgid =", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotEqualTo(String value) {
            addCriterion("updprgid <>", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidGreaterThan(String value) {
            addCriterion("updprgid >", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidGreaterThanOrEqualTo(String value) {
            addCriterion("updprgid >=", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLessThan(String value) {
            addCriterion("updprgid <", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLessThanOrEqualTo(String value) {
            addCriterion("updprgid <=", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidLike(String value) {
            addCriterion("updprgid like", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotLike(String value) {
            addCriterion("updprgid not like", value, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidIn(List<String> values) {
            addCriterion("updprgid in", values, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotIn(List<String> values) {
            addCriterion("updprgid not in", values, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidBetween(String value1, String value2) {
            addCriterion("updprgid between", value1, value2, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdprgidNotBetween(String value1, String value2) {
            addCriterion("updprgid not between", value1, value2, "updprgid");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIsNull() {
            addCriterion("updipaddr is null");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIsNotNull() {
            addCriterion("updipaddr is not null");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrEqualTo(String value) {
            addCriterion("updipaddr =", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotEqualTo(String value) {
            addCriterion("updipaddr <>", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrGreaterThan(String value) {
            addCriterion("updipaddr >", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrGreaterThanOrEqualTo(String value) {
            addCriterion("updipaddr >=", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLessThan(String value) {
            addCriterion("updipaddr <", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLessThanOrEqualTo(String value) {
            addCriterion("updipaddr <=", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrLike(String value) {
            addCriterion("updipaddr like", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotLike(String value) {
            addCriterion("updipaddr not like", value, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrIn(List<String> values) {
            addCriterion("updipaddr in", values, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotIn(List<String> values) {
            addCriterion("updipaddr not in", values, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrBetween(String value1, String value2) {
            addCriterion("updipaddr between", value1, value2, "updipaddr");
            return (Criteria) this;
        }

        public Criteria andUpdipaddrNotBetween(String value1, String value2) {
            addCriterion("updipaddr not between", value1, value2, "updipaddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 22 17:43:52 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lb01_pt.lmm91_cdnm
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}