package com.feast.kanjo.entity;

import com.feast.kanjo.entity.Vlbm84ShohinCdUpd;
import com.feast.kanjo.entity.Vlbm84ShohinCdUpdExample;
import com.feast.kanjo.entity.Vlbm84ShohinCdUpdKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Vlbm84ShohinCdUpdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int countByExample(Vlbm84ShohinCdUpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByExample(Vlbm84ShohinCdUpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int deleteByPrimaryKey(Vlbm84ShohinCdUpdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insert(Vlbm84ShohinCdUpd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int insertSelective(Vlbm84ShohinCdUpd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    List<Vlbm84ShohinCdUpd> selectByExample(Vlbm84ShohinCdUpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    Vlbm84ShohinCdUpd selectByPrimaryKey(Vlbm84ShohinCdUpdKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Vlbm84ShohinCdUpd record, @Param("example") Vlbm84ShohinCdUpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByExample(@Param("record") Vlbm84ShohinCdUpd record, @Param("example") Vlbm84ShohinCdUpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKeySelective(Vlbm84ShohinCdUpd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb01_pt.vlbm84_shohin_cd_upd
     *
     * @mbggenerated Mon Jan 22 17:43:52 CST 2018
     */
    int updateByPrimaryKey(Vlbm84ShohinCdUpd record);
}