DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (
      EMPLOYEE_ID numeric(20) not null
    , EMPLOYEE_NAME character varying(255)
    , EMPLOYEE_ADDRESS character varying(255)
    , EMPLOYEE_BIRTH timestamp
    , EMPLOYEE_SALARY numeric(5)
, CONSTRAINT EMPLOYEE_pkey PRIMARY KEY (EMPLOYEE_ID)
);

COMMENT ON TABLE EMPLOYEE IS 'EMPLOYEE';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_ID IS 'EMPLOYEE_ID';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_NAME IS 'EMPLOYEE_NAME';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_ADDRESS IS 'EMPLOYEE_ADDRESS';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_BIRTH IS 'EMPLOYEE_BIRTH';
COMMENT ON COLUMN EMPLOYEE.EMPLOYEE_SALARY IS 'EMPLOYEE_SALARY';



insert into employee values('1','Rockey','Beijing', now(), 2000);
insert into employee values('2','Jose','Shanghai', now(), 5000);